/*
 * Generated by lalc v0.3 — the LAL compiler.
 *
 * Entry rule: classify
 * Vector dim: 8
 * Rules emitted (all transitively-reachable; rule calls are real C calls):
 *   - classify
 *
 * Specializations applied at compile time:
 *   - BOUND: only used dimensions retained in concept vectors
 *   - DOT: fully unrolled (scalar) or SIMD (AVX2/NEON) when width >= 8
 *   - BIND/BUNDLE/PERMUTE: element-wise, fully unrolled
 *   - MEMORY recall: compiled to fixed dot products + weighted sum
 *   - Rule calls: real C function calls (supports true recursion)
 *   - argmax: flat comparison chain, no dispatch
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#if defined(__AVX2__) || defined(__AVX__)
#include <immintrin.h>
#elif defined(__ARM_NEON) || defined(__ARM_NEON__)
#include <arm_neon.h>
#endif

/* === Masked concept vectors (BOUND applied at compile time) === */
static const float car__machine_dims[4] = {0.900000f, 0.800000f, 0.700000f, 0.600000f};
static const float cat__animal_dims[4] = {1.000000f, 0.200000f, 0.700000f, 0.800000f};
static const float dog__animal_dims[4] = {0.800000f, 0.300000f, 0.600000f, 0.700000f};
static const float vehicle__machine_dims[4] = {0.900000f, 0.900000f, 0.600000f, 0.700000f};

/* === Forward declarations === */
void rule_classify_v0(const float* query, int* out_best_idx);
void rule_classify(const float* query, int* out_best_idx);

/* rule classify_v0 */
void rule_classify_v0(const float* query, int* out_best_idx) {
    float query__animal_dims[4] = {query[0], query[2], query[3], query[6]};
    float query__machine_dims[4] = {query[1], query[2], query[4], query[7]};
    float best_score_0 = (query__animal_dims[0] * cat__animal_dims[0] + query__animal_dims[1] * cat__animal_dims[1] + query__animal_dims[2] * cat__animal_dims[2] + query__animal_dims[3] * cat__animal_dims[3]);  /* cat */
    float best_score_1 = (query__animal_dims[0] * dog__animal_dims[0] + query__animal_dims[1] * dog__animal_dims[1] + query__animal_dims[2] * dog__animal_dims[2] + query__animal_dims[3] * dog__animal_dims[3]);  /* dog */
    float best_score_2 = (query__machine_dims[0] * car__machine_dims[0] + query__machine_dims[1] * car__machine_dims[1] + query__machine_dims[2] * car__machine_dims[2] + query__machine_dims[3] * car__machine_dims[3]);  /* car */
    float best_score_3 = (query__machine_dims[0] * vehicle__machine_dims[0] + query__machine_dims[1] * vehicle__machine_dims[1] + query__machine_dims[2] * vehicle__machine_dims[2] + query__machine_dims[3] * vehicle__machine_dims[3]);  /* vehicle */
    *out_best_idx = 0;
    float __best = best_score_0;
    if (best_score_1 > __best) { __best = best_score_1; *out_best_idx = 1; }
    if (best_score_2 > __best) { __best = best_score_2; *out_best_idx = 2; }
    if (best_score_3 > __best) { __best = best_score_3; *out_best_idx = 3; }

    /* Outputs */
}

/* dispatcher for rule classify (1 variant(s)) */
void rule_classify(const float* query, int* out_best_idx) {
    rule_classify_v0(query, out_best_idx);
    return;
    /* no variant matched: passthrough input */
    *out_best_idx = 0;
}

int main(int argc, char** argv) {
    float q[8];
    if (argc < 9) {
        fprintf(stderr, "usage: classify v0 v1 ... v7\n");
        return 1;
    }
    for (int i = 0; i < 8; i++) q[i] = (float)atof(argv[i+1]);
    int out_best_idx = -1;
    rule_classify(q, &out_best_idx);
    printf("%d\n", out_best_idx);
    return 0;
}
