/*
 * Generated by lalc v0.3 — the LAL compiler.
 *
 * Entry rule: main
 * Vector dim: 8
 * Rules emitted (all transitively-reachable; rule calls are real C calls):
 *   - follow
 *   - main
 *
 * Specializations applied at compile time:
 *   - BOUND: only used dimensions retained in concept vectors
 *   - DOT: fully unrolled (scalar) or SIMD (AVX2/NEON) when width >= 8
 *   - BIND/BUNDLE/PERMUTE: element-wise, fully unrolled
 *   - MEMORY recall: compiled to fixed dot products + weighted sum
 *   - Rule calls: real C function calls (supports true recursion)
 *   - argmax: flat comparison chain, no dispatch
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#if defined(__AVX2__) || defined(__AVX__)
#include <immintrin.h>
#elif defined(__ARM_NEON) || defined(__ARM_NEON__)
#include <arm_neon.h>
#endif

/* === Concept vectors (full dim, used by VSA ops and MEMORY recall) ===
 * Only concepts referenced by bind/bundle/permute/recall/unbounded-dot are emitted. */
static const float concept_node_a[8] = {1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f};
static const float concept_node_b[8] = {0.000000f, 1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f};
static const float concept_node_c[8] = {0.000000f, 0.000000f, 1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f};
static const float concept_terminal[8] = {0.000000f, 0.000000f, 0.000000f, 1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f};

/* === Masked concept vectors (BOUND applied at compile time) === */
static const float node_a__all_dims[8] = {1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f};
static const float node_b__all_dims[8] = {0.000000f, 1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f};
static const float node_c__all_dims[8] = {0.000000f, 0.000000f, 1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f};
static const float terminal__all_dims[8] = {0.000000f, 0.000000f, 0.000000f, 1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f};

/* === SIMD dot-product helpers (AVX2 on x86_64, NEON on arm64) ===
 * Compiled in only when the target supports them; scalar fallback otherwise. */
/* dot product of two float[8] — SIMD-accelerated */
static inline float _lal_dot_simd_8(const float* a, const float* b) {
    float result = 0.0f;
#if defined(__AVX2__) || defined(__AVX__)
    {
        __m256 acc = _mm256_setzero_ps();
        __m256 va_0 = _mm256_loadu_ps(a + 0);
        __m256 vb_0 = _mm256_loadu_ps(b + 0);
        acc = _mm256_fmadd_ps(va_0, vb_0, acc);
        __m128 lo = _mm256_castps256_ps128(acc);
        __m128 hi = _mm256_extractf128_ps(acc, 1);
        __m128 s = _mm_add_ps(lo, hi);
        s = _mm_hadd_ps(s, s);
        s = _mm_hadd_ps(s, s);
        result = _mm_cvtss_f32(s);
    }
#elif defined(__ARM_NEON) || defined(__ARM_NEON__)
    {
        float32x4_t acc = vdupq_n_f32(0.0f);
        float32x4_t va_0 = vld1q_f32(a + 0);
        float32x4_t vb_0 = vld1q_f32(b + 0);
        acc = vfmaq_f32(acc, va_0, vb_0);
        float32x4_t va_1 = vld1q_f32(a + 4);
        float32x4_t vb_1 = vld1q_f32(b + 4);
        acc = vfmaq_f32(acc, va_1, vb_1);
        float tmp[4]; vst1q_f32(tmp, acc);
        result = tmp[0] + tmp[1] + tmp[2] + tmp[3];
    }
#else
    result += a[0] * b[0];
    result += a[1] * b[1];
    result += a[2] * b[2];
    result += a[3] * b[3];
    result += a[4] * b[4];
    result += a[5] * b[5];
    result += a[6] * b[6];
    result += a[7] * b[7];
#endif
    return result;
}

/* === Forward declarations === */
void rule_follow_v0(const float* current, float* out_result);
void rule_follow(const float* current, float* out_result);
void rule_main_v0(const float* query, int* out_best_idx);
void rule_main(const float* query, int* out_best_idx);

/* rule follow_v0 */
/* guard: ECall(func='lt', args=[ERelateCall(name='sim', args=[EVar(name='current'), EVar(name='terminal')]), EFloat(val=0.5)]) */
void rule_follow_v0(const float* current, float* out_result) {
    float current__all_dims[8] = {current[0], current[1], current[2], current[3], current[4], current[5], current[6], current[7]};
    if (!(((_lal_dot_simd_8(current__all_dims, terminal__all_dims) < 0.500000f) ? 1.0f : 0.0f))) {
        /* guard failed: passthrough input as output (base case) */
        for (int i = 0; i < 8; i++) out_result[i] = current[i];
        return;
    }
    float next[8] = {0};
    float __weights[4] = {0};
    float __total_weight = 0.0f;
    __weights[0] = (current[0] * concept_node_a[0] + current[1] * concept_node_a[1] + current[2] * concept_node_a[2] + current[3] * concept_node_a[3] + current[4] * concept_node_a[4] + current[5] * concept_node_a[5] + current[6] * concept_node_a[6] + current[7] * concept_node_a[7]);
    if (__weights[0] < 0.0f) __weights[0] = 0.0f;
    __total_weight += __weights[0];
    __weights[1] = (current[0] * concept_node_b[0] + current[1] * concept_node_b[1] + current[2] * concept_node_b[2] + current[3] * concept_node_b[3] + current[4] * concept_node_b[4] + current[5] * concept_node_b[5] + current[6] * concept_node_b[6] + current[7] * concept_node_b[7]);
    if (__weights[1] < 0.0f) __weights[1] = 0.0f;
    __total_weight += __weights[1];
    __weights[2] = (current[0] * concept_node_c[0] + current[1] * concept_node_c[1] + current[2] * concept_node_c[2] + current[3] * concept_node_c[3] + current[4] * concept_node_c[4] + current[5] * concept_node_c[5] + current[6] * concept_node_c[6] + current[7] * concept_node_c[7]);
    if (__weights[2] < 0.0f) __weights[2] = 0.0f;
    __total_weight += __weights[2];
    __weights[3] = (current[0] * concept_terminal[0] + current[1] * concept_terminal[1] + current[2] * concept_terminal[2] + current[3] * concept_terminal[3] + current[4] * concept_terminal[4] + current[5] * concept_terminal[5] + current[6] * concept_terminal[6] + current[7] * concept_terminal[7]);
    if (__weights[3] < 0.0f) __weights[3] = 0.0f;
    __total_weight += __weights[3];
    if (__total_weight > 1e-9f) {
        next[0] = (__weights[0] * concept_node_b[0] + __weights[1] * concept_node_c[0] + __weights[2] * concept_terminal[0] + __weights[3] * concept_terminal[0]) / __total_weight;
        next[1] = (__weights[0] * concept_node_b[1] + __weights[1] * concept_node_c[1] + __weights[2] * concept_terminal[1] + __weights[3] * concept_terminal[1]) / __total_weight;
        next[2] = (__weights[0] * concept_node_b[2] + __weights[1] * concept_node_c[2] + __weights[2] * concept_terminal[2] + __weights[3] * concept_terminal[2]) / __total_weight;
        next[3] = (__weights[0] * concept_node_b[3] + __weights[1] * concept_node_c[3] + __weights[2] * concept_terminal[3] + __weights[3] * concept_terminal[3]) / __total_weight;
        next[4] = (__weights[0] * concept_node_b[4] + __weights[1] * concept_node_c[4] + __weights[2] * concept_terminal[4] + __weights[3] * concept_terminal[4]) / __total_weight;
        next[5] = (__weights[0] * concept_node_b[5] + __weights[1] * concept_node_c[5] + __weights[2] * concept_terminal[5] + __weights[3] * concept_terminal[5]) / __total_weight;
        next[6] = (__weights[0] * concept_node_b[6] + __weights[1] * concept_node_c[6] + __weights[2] * concept_terminal[6] + __weights[3] * concept_terminal[6]) / __total_weight;
        next[7] = (__weights[0] * concept_node_b[7] + __weights[1] * concept_node_c[7] + __weights[2] * concept_terminal[7] + __weights[3] * concept_terminal[7]) / __total_weight;
    }
    float result[8] = {0};
    rule_follow(next, result);

    /* Outputs */
    for (int i = 0; i < 8; i++) out_result[i] = result[i];
}

/* dispatcher for rule follow (1 variant(s)) */
void rule_follow(const float* current, float* out_result) {
    float current__all_dims[8] = {current[0], current[1], current[2], current[3], current[4], current[5], current[6], current[7]};
    if (((_lal_dot_simd_8(current__all_dims, terminal__all_dims) < 0.500000f) ? 1.0f : 0.0f)) {
        rule_follow_v0(current, out_result);
        return;
    }
    /* no variant matched: passthrough input */
    for (int i = 0; i < 8; i++) out_result[i] = current[i];
}

/* rule main_v0 */
void rule_main_v0(const float* query, int* out_best_idx) {
    float dest[8] = {0};
    rule_follow(query, dest);
    float best_score_0 = (dest[0] * node_a__all_dims[0] + dest[1] * node_a__all_dims[1] + dest[2] * node_a__all_dims[2] + dest[3] * node_a__all_dims[3] + dest[4] * node_a__all_dims[4] + dest[5] * node_a__all_dims[5] + dest[6] * node_a__all_dims[6] + dest[7] * node_a__all_dims[7]);  /* node_a */
    float best_score_1 = (dest[0] * node_b__all_dims[0] + dest[1] * node_b__all_dims[1] + dest[2] * node_b__all_dims[2] + dest[3] * node_b__all_dims[3] + dest[4] * node_b__all_dims[4] + dest[5] * node_b__all_dims[5] + dest[6] * node_b__all_dims[6] + dest[7] * node_b__all_dims[7]);  /* node_b */
    float best_score_2 = (dest[0] * node_c__all_dims[0] + dest[1] * node_c__all_dims[1] + dest[2] * node_c__all_dims[2] + dest[3] * node_c__all_dims[3] + dest[4] * node_c__all_dims[4] + dest[5] * node_c__all_dims[5] + dest[6] * node_c__all_dims[6] + dest[7] * node_c__all_dims[7]);  /* node_c */
    float best_score_3 = (dest[0] * terminal__all_dims[0] + dest[1] * terminal__all_dims[1] + dest[2] * terminal__all_dims[2] + dest[3] * terminal__all_dims[3] + dest[4] * terminal__all_dims[4] + dest[5] * terminal__all_dims[5] + dest[6] * terminal__all_dims[6] + dest[7] * terminal__all_dims[7]);  /* terminal */
    *out_best_idx = 0;
    float __best = best_score_0;
    if (best_score_1 > __best) { __best = best_score_1; *out_best_idx = 1; }
    if (best_score_2 > __best) { __best = best_score_2; *out_best_idx = 2; }
    if (best_score_3 > __best) { __best = best_score_3; *out_best_idx = 3; }

    /* Outputs */
}

/* dispatcher for rule main (1 variant(s)) */
void rule_main(const float* query, int* out_best_idx) {
    rule_main_v0(query, out_best_idx);
    return;
    /* no variant matched: passthrough input */
    *out_best_idx = 0;
}

int main(int argc, char** argv) {
    float q[8];
    if (argc < 9) {
        fprintf(stderr, "usage: main v0 v1 ... v7\n");
        return 1;
    }
    for (int i = 0; i < 8; i++) q[i] = (float)atof(argv[i+1]);
    int out_best_idx = -1;
    rule_main(q, &out_best_idx);
    printf("%d\n", out_best_idx);
    return 0;
}
