/*
 * Generated by lalc v0.3 — the LAL compiler.
 *
 * Entry rule: main
 * Vector dim: 8
 * Rules emitted (all transitively-reachable; rule calls are real C calls):
 *   - main
 *   - shift_once
 *   - shift_thrice
 *
 * Specializations applied at compile time:
 *   - BOUND: only used dimensions retained in concept vectors
 *   - DOT: fully unrolled (scalar) or SIMD (AVX2/NEON) when width >= 8
 *   - BIND/BUNDLE/PERMUTE: element-wise, fully unrolled
 *   - MEMORY recall: compiled to fixed dot products + weighted sum
 *   - Rule calls: real C function calls (supports true recursion)
 *   - argmax: flat comparison chain, no dispatch
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#if defined(__AVX2__) || defined(__AVX__)
#include <immintrin.h>
#elif defined(__ARM_NEON) || defined(__ARM_NEON__)
#include <arm_neon.h>
#endif

/* === Masked concept vectors (BOUND applied at compile time) === */
static const float base__all_dims[8] = {1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f};
static const float target__all_dims[8] = {0.000000f, 0.000000f, 0.000000f, 1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f};

/* === SIMD dot-product helpers (AVX2 on x86_64, NEON on arm64) ===
 * Compiled in only when the target supports them; scalar fallback otherwise. */
/* dot product of two float[8] — SIMD-accelerated */
static inline float _lal_dot_simd_8(const float* a, const float* b) {
    float result = 0.0f;
#if defined(__AVX2__) || defined(__AVX__)
    {
        __m256 acc = _mm256_setzero_ps();
        __m256 va_0 = _mm256_loadu_ps(a + 0);
        __m256 vb_0 = _mm256_loadu_ps(b + 0);
        acc = _mm256_fmadd_ps(va_0, vb_0, acc);
        __m128 lo = _mm256_castps256_ps128(acc);
        __m128 hi = _mm256_extractf128_ps(acc, 1);
        __m128 s = _mm_add_ps(lo, hi);
        s = _mm_hadd_ps(s, s);
        s = _mm_hadd_ps(s, s);
        result = _mm_cvtss_f32(s);
    }
#elif defined(__ARM_NEON) || defined(__ARM_NEON__)
    {
        float32x4_t acc = vdupq_n_f32(0.0f);
        float32x4_t va_0 = vld1q_f32(a + 0);
        float32x4_t vb_0 = vld1q_f32(b + 0);
        acc = vfmaq_f32(acc, va_0, vb_0);
        float32x4_t va_1 = vld1q_f32(a + 4);
        float32x4_t vb_1 = vld1q_f32(b + 4);
        acc = vfmaq_f32(acc, va_1, vb_1);
        float tmp[4]; vst1q_f32(tmp, acc);
        result = tmp[0] + tmp[1] + tmp[2] + tmp[3];
    }
#else
    result += a[0] * b[0];
    result += a[1] * b[1];
    result += a[2] * b[2];
    result += a[3] * b[3];
    result += a[4] * b[4];
    result += a[5] * b[5];
    result += a[6] * b[6];
    result += a[7] * b[7];
#endif
    return result;
}

/* === Forward declarations === */
void rule_main_v0(const float* query, int* out_best_idx);
void rule_main(const float* query, int* out_best_idx);
void rule_shift_once_v0(const float* v, float* out_result);
void rule_shift_once(const float* v, float* out_result);
void rule_shift_thrice_v0(const float* v, float* out_thrice);
void rule_shift_thrice(const float* v, float* out_thrice);

/* rule main_v0 */
void rule_main_v0(const float* query, int* out_best_idx) {
    float shifted[8] = {0};
    rule_shift_thrice(query, shifted);
    float best_score_0 = (shifted[0] * target__all_dims[0] + shifted[1] * target__all_dims[1] + shifted[2] * target__all_dims[2] + shifted[3] * target__all_dims[3] + shifted[4] * target__all_dims[4] + shifted[5] * target__all_dims[5] + shifted[6] * target__all_dims[6] + shifted[7] * target__all_dims[7]);  /* target */
    float best_score_1 = (shifted[0] * base__all_dims[0] + shifted[1] * base__all_dims[1] + shifted[2] * base__all_dims[2] + shifted[3] * base__all_dims[3] + shifted[4] * base__all_dims[4] + shifted[5] * base__all_dims[5] + shifted[6] * base__all_dims[6] + shifted[7] * base__all_dims[7]);  /* base */
    *out_best_idx = 0;
    float __best = best_score_0;
    if (best_score_1 > __best) { __best = best_score_1; *out_best_idx = 1; }

    /* Outputs */
}

/* dispatcher for rule main (1 variant(s)) */
void rule_main(const float* query, int* out_best_idx) {
    rule_main_v0(query, out_best_idx);
    return;
    /* no variant matched: passthrough input */
    *out_best_idx = 0;
}

/* rule shift_once_v0 */
void rule_shift_once_v0(const float* v, float* out_result) {
    float result[8] = {0};
    result[0] = v[7];
    result[1] = v[0];
    result[2] = v[1];
    result[3] = v[2];
    result[4] = v[3];
    result[5] = v[4];
    result[6] = v[5];
    result[7] = v[6];

    /* Outputs */
    for (int i = 0; i < 8; i++) out_result[i] = result[i];
}

/* dispatcher for rule shift_once (1 variant(s)) */
void rule_shift_once(const float* v, float* out_result) {
    rule_shift_once_v0(v, out_result);
    return;
    /* no variant matched: passthrough input */
    for (int i = 0; i < 8; i++) out_result[i] = v[i];
}

/* rule shift_thrice_v0 */
void rule_shift_thrice_v0(const float* v, float* out_thrice) {
    float once[8] = {0};
    rule_shift_once(v, once);
    float twice[8] = {0};
    rule_shift_once(once, twice);
    float thrice[8] = {0};
    rule_shift_once(twice, thrice);

    /* Outputs */
    for (int i = 0; i < 8; i++) out_thrice[i] = thrice[i];
}

/* dispatcher for rule shift_thrice (1 variant(s)) */
void rule_shift_thrice(const float* v, float* out_thrice) {
    rule_shift_thrice_v0(v, out_thrice);
    return;
    /* no variant matched: passthrough input */
    for (int i = 0; i < 8; i++) out_thrice[i] = v[i];
}

int main(int argc, char** argv) {
    float q[8];
    if (argc < 9) {
        fprintf(stderr, "usage: shift_thrice v0 v1 ... v7\n");
        return 1;
    }
    for (int i = 0; i < 8; i++) q[i] = (float)atof(argv[i+1]);
    int out_best_idx = -1;
    rule_main(q, &out_best_idx);
    printf("%d\n", out_best_idx);
    return 0;
}
