/*
 * Generated by lalc v0.3 — the LAL compiler.
 *
 * Entry rule: main
 * Vector dim: 8
 * Rules emitted (all transitively-reachable; rule calls are real C calls):
 *   - conclude_mortal
 *   - lookup_is
 *   - lookup_is_a
 *   - main
 *
 * Specializations applied at compile time:
 *   - BOUND: only used dimensions retained in concept vectors
 *   - DOT: fully unrolled (scalar) or SIMD (AVX2/NEON) when width >= 8
 *   - BIND/BUNDLE/PERMUTE: element-wise, fully unrolled
 *   - MEMORY recall: compiled to fixed dot products + weighted sum
 *   - Rule calls: real C function calls (supports true recursion)
 *   - argmax: flat comparison chain, no dispatch
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#if defined(__AVX2__) || defined(__AVX__)
#include <immintrin.h>
#elif defined(__ARM_NEON) || defined(__ARM_NEON__)
#include <arm_neon.h>
#endif

/* === Concept vectors (full dim, used by VSA ops and MEMORY recall) ===
 * Only concepts referenced by bind/bundle/permute/recall/unbounded-dot are emitted. */
static const float concept_aristotle[8] = {0.500000f, 0.700000f, 0.400000f, 0.300000f, 0.400000f, 0.300000f, 0.600000f, 0.400000f};
static const float concept_human[8] = {0.700000f, 0.600000f, 0.500000f, 0.400000f, 0.300000f, 0.200000f, 0.500000f, 0.300000f};
static const float concept_mortal[8] = {0.600000f, 0.500000f, 0.400000f, 0.500000f, 0.400000f, 0.300000f, 0.400000f, 0.500000f};
static const float concept_plato[8] = {0.600000f, 0.500000f, 0.300000f, 0.500000f, 0.200000f, 0.200000f, 0.400000f, 0.300000f};
static const float concept_socrates[8] = {0.700000f, 0.600000f, 0.200000f, 0.400000f, 0.300000f, 0.100000f, 0.500000f, 0.200000f};
static const float concept_stone[8] = {0.100000f, 0.200000f, 0.100000f, 0.700000f, 0.800000f, 0.600000f, 0.100000f, 0.200000f};

/* === Masked concept vectors (BOUND applied at compile time) === */
static const float human__animacy_dims[4] = {0.700000f, 0.600000f, 0.500000f, 0.500000f};
static const float mortal__animacy_dims[4] = {0.600000f, 0.500000f, 0.400000f, 0.400000f};
static const float socrates__animacy_dims[4] = {0.700000f, 0.600000f, 0.200000f, 0.500000f};
static const float stone__animacy_dims[4] = {0.100000f, 0.200000f, 0.100000f, 0.100000f};

/* === Forward declarations === */
void rule_conclude_mortal_v0(const float* subject, float* out_prop);
void rule_conclude_mortal(const float* subject, float* out_prop);
void rule_lookup_is_v0(const float* category, float* out_property);
void rule_lookup_is(const float* category, float* out_property);
void rule_lookup_is_a_v0(const float* subject, float* out_category);
void rule_lookup_is_a(const float* subject, float* out_category);
void rule_main_v0(const float* query, int* out_best_idx);
void rule_main(const float* query, int* out_best_idx);

/* rule conclude_mortal_v0 */
void rule_conclude_mortal_v0(const float* subject, float* out_prop) {
    float cat[8] = {0};
    rule_lookup_is_a(subject, cat);
    float prop[8] = {0};
    rule_lookup_is(cat, prop);

    /* Outputs */
    for (int i = 0; i < 8; i++) out_prop[i] = prop[i];
}

/* dispatcher for rule conclude_mortal (1 variant(s)) */
void rule_conclude_mortal(const float* subject, float* out_prop) {
    rule_conclude_mortal_v0(subject, out_prop);
    return;
    /* no variant matched: passthrough input */
    for (int i = 0; i < 8; i++) out_prop[i] = subject[i];
}

/* rule lookup_is_v0 */
void rule_lookup_is_v0(const float* category, float* out_property) {
    float property[8] = {0};
    float __weights[1] = {0};
    float __total_weight = 0.0f;
    __weights[0] = (category[0] * concept_human[0] + category[1] * concept_human[1] + category[2] * concept_human[2] + category[3] * concept_human[3] + category[4] * concept_human[4] + category[5] * concept_human[5] + category[6] * concept_human[6] + category[7] * concept_human[7]);
    if (__weights[0] < 0.0f) __weights[0] = 0.0f;
    __total_weight += __weights[0];
    if (__total_weight > 1e-9f) {
        property[0] = (__weights[0] * concept_mortal[0]) / __total_weight;
        property[1] = (__weights[0] * concept_mortal[1]) / __total_weight;
        property[2] = (__weights[0] * concept_mortal[2]) / __total_weight;
        property[3] = (__weights[0] * concept_mortal[3]) / __total_weight;
        property[4] = (__weights[0] * concept_mortal[4]) / __total_weight;
        property[5] = (__weights[0] * concept_mortal[5]) / __total_weight;
        property[6] = (__weights[0] * concept_mortal[6]) / __total_weight;
        property[7] = (__weights[0] * concept_mortal[7]) / __total_weight;
    }

    /* Outputs */
    for (int i = 0; i < 8; i++) out_property[i] = property[i];
}

/* dispatcher for rule lookup_is (1 variant(s)) */
void rule_lookup_is(const float* category, float* out_property) {
    rule_lookup_is_v0(category, out_property);
    return;
    /* no variant matched: passthrough input */
    for (int i = 0; i < 8; i++) out_property[i] = category[i];
}

/* rule lookup_is_a_v0 */
void rule_lookup_is_a_v0(const float* subject, float* out_category) {
    float category[8] = {0};
    float __weights[4] = {0};
    float __total_weight = 0.0f;
    __weights[0] = (subject[0] * concept_socrates[0] + subject[1] * concept_socrates[1] + subject[2] * concept_socrates[2] + subject[3] * concept_socrates[3] + subject[4] * concept_socrates[4] + subject[5] * concept_socrates[5] + subject[6] * concept_socrates[6] + subject[7] * concept_socrates[7]);
    if (__weights[0] < 0.0f) __weights[0] = 0.0f;
    __total_weight += __weights[0];
    __weights[1] = (subject[0] * concept_plato[0] + subject[1] * concept_plato[1] + subject[2] * concept_plato[2] + subject[3] * concept_plato[3] + subject[4] * concept_plato[4] + subject[5] * concept_plato[5] + subject[6] * concept_plato[6] + subject[7] * concept_plato[7]);
    if (__weights[1] < 0.0f) __weights[1] = 0.0f;
    __total_weight += __weights[1];
    __weights[2] = (subject[0] * concept_aristotle[0] + subject[1] * concept_aristotle[1] + subject[2] * concept_aristotle[2] + subject[3] * concept_aristotle[3] + subject[4] * concept_aristotle[4] + subject[5] * concept_aristotle[5] + subject[6] * concept_aristotle[6] + subject[7] * concept_aristotle[7]);
    if (__weights[2] < 0.0f) __weights[2] = 0.0f;
    __total_weight += __weights[2];
    __weights[3] = (subject[0] * concept_stone[0] + subject[1] * concept_stone[1] + subject[2] * concept_stone[2] + subject[3] * concept_stone[3] + subject[4] * concept_stone[4] + subject[5] * concept_stone[5] + subject[6] * concept_stone[6] + subject[7] * concept_stone[7]);
    if (__weights[3] < 0.0f) __weights[3] = 0.0f;
    __total_weight += __weights[3];
    if (__total_weight > 1e-9f) {
        category[0] = (__weights[0] * concept_human[0] + __weights[1] * concept_human[0] + __weights[2] * concept_human[0] + __weights[3] * concept_stone[0]) / __total_weight;
        category[1] = (__weights[0] * concept_human[1] + __weights[1] * concept_human[1] + __weights[2] * concept_human[1] + __weights[3] * concept_stone[1]) / __total_weight;
        category[2] = (__weights[0] * concept_human[2] + __weights[1] * concept_human[2] + __weights[2] * concept_human[2] + __weights[3] * concept_stone[2]) / __total_weight;
        category[3] = (__weights[0] * concept_human[3] + __weights[1] * concept_human[3] + __weights[2] * concept_human[3] + __weights[3] * concept_stone[3]) / __total_weight;
        category[4] = (__weights[0] * concept_human[4] + __weights[1] * concept_human[4] + __weights[2] * concept_human[4] + __weights[3] * concept_stone[4]) / __total_weight;
        category[5] = (__weights[0] * concept_human[5] + __weights[1] * concept_human[5] + __weights[2] * concept_human[5] + __weights[3] * concept_stone[5]) / __total_weight;
        category[6] = (__weights[0] * concept_human[6] + __weights[1] * concept_human[6] + __weights[2] * concept_human[6] + __weights[3] * concept_stone[6]) / __total_weight;
        category[7] = (__weights[0] * concept_human[7] + __weights[1] * concept_human[7] + __weights[2] * concept_human[7] + __weights[3] * concept_stone[7]) / __total_weight;
    }

    /* Outputs */
    for (int i = 0; i < 8; i++) out_category[i] = category[i];
}

/* dispatcher for rule lookup_is_a (1 variant(s)) */
void rule_lookup_is_a(const float* subject, float* out_category) {
    rule_lookup_is_a_v0(subject, out_category);
    return;
    /* no variant matched: passthrough input */
    for (int i = 0; i < 8; i++) out_category[i] = subject[i];
}

/* rule main_v0 */
void rule_main_v0(const float* query, int* out_best_idx) {
    float property[8] = {0};
    rule_conclude_mortal(query, property);
    float best_score_0 = (property[0] * mortal__animacy_dims[0] + property[1] * mortal__animacy_dims[1] + property[2] * mortal__animacy_dims[2] + property[6] * mortal__animacy_dims[3]);  /* mortal */
    float best_score_1 = (property[0] * human__animacy_dims[0] + property[1] * human__animacy_dims[1] + property[2] * human__animacy_dims[2] + property[6] * human__animacy_dims[3]);  /* human */
    float best_score_2 = (property[0] * stone__animacy_dims[0] + property[1] * stone__animacy_dims[1] + property[2] * stone__animacy_dims[2] + property[6] * stone__animacy_dims[3]);  /* stone */
    float best_score_3 = (property[0] * socrates__animacy_dims[0] + property[1] * socrates__animacy_dims[1] + property[2] * socrates__animacy_dims[2] + property[6] * socrates__animacy_dims[3]);  /* socrates */
    *out_best_idx = 0;
    float __best = best_score_0;
    if (best_score_1 > __best) { __best = best_score_1; *out_best_idx = 1; }
    if (best_score_2 > __best) { __best = best_score_2; *out_best_idx = 2; }
    if (best_score_3 > __best) { __best = best_score_3; *out_best_idx = 3; }

    /* Outputs */
}

/* dispatcher for rule main (1 variant(s)) */
void rule_main(const float* query, int* out_best_idx) {
    rule_main_v0(query, out_best_idx);
    return;
    /* no variant matched: passthrough input */
    *out_best_idx = 0;
}

int main(int argc, char** argv) {
    float q[8];
    if (argc < 9) {
        fprintf(stderr, "usage: main v0 v1 ... v7\n");
        return 1;
    }
    for (int i = 0; i < 8; i++) q[i] = (float)atof(argv[i+1]);
    int out_best_idx = -1;
    rule_main(q, &out_best_idx);
    printf("%d\n", out_best_idx);
    return 0;
}
