/*
 * Generated by lalc v0.3 — the LAL compiler.
 *
 * Entry rule: main
 * Vector dim: 8
 * Rules emitted (all transitively-reachable; rule calls are real C calls):
 *   - encode
 *   - main
 *
 * Specializations applied at compile time:
 *   - BOUND: only used dimensions retained in concept vectors
 *   - DOT: fully unrolled (scalar) or SIMD (AVX2/NEON) when width >= 8
 *   - BIND/BUNDLE/PERMUTE: element-wise, fully unrolled
 *   - MEMORY recall: compiled to fixed dot products + weighted sum
 *   - Rule calls: real C function calls (supports true recursion)
 *   - argmax: flat comparison chain, no dispatch
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#if defined(__AVX2__) || defined(__AVX__)
#include <immintrin.h>
#elif defined(__ARM_NEON) || defined(__ARM_NEON__)
#include <arm_neon.h>
#endif

/* === Concept vectors (full dim, used by VSA ops and MEMORY recall) ===
 * Only concepts referenced by bind/bundle/permute/recall/unbounded-dot are emitted. */
static const float concept_role_action[8] = {0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.500000f, 0.500000f, 0.500000f, 0.500000f};
static const float concept_role_agent[8] = {0.500000f, 0.500000f, 0.500000f, 0.500000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f};

/* === Masked concept vectors (BOUND applied at compile time) === */
static const float alice__identity[8] = {1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f};
static const float bob__identity[8] = {0.000000f, 1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f};
static const float carol__identity[8] = {0.000000f, 0.000000f, 1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f};

/* === SIMD dot-product helpers (AVX2 on x86_64, NEON on arm64) ===
 * Compiled in only when the target supports them; scalar fallback otherwise. */
/* dot product of two float[8] — SIMD-accelerated */
static inline float _lal_dot_simd_8(const float* a, const float* b) {
    float result = 0.0f;
#if defined(__AVX2__) || defined(__AVX__)
    {
        __m256 acc = _mm256_setzero_ps();
        __m256 va_0 = _mm256_loadu_ps(a + 0);
        __m256 vb_0 = _mm256_loadu_ps(b + 0);
        acc = _mm256_fmadd_ps(va_0, vb_0, acc);
        __m128 lo = _mm256_castps256_ps128(acc);
        __m128 hi = _mm256_extractf128_ps(acc, 1);
        __m128 s = _mm_add_ps(lo, hi);
        s = _mm_hadd_ps(s, s);
        s = _mm_hadd_ps(s, s);
        result = _mm_cvtss_f32(s);
    }
#elif defined(__ARM_NEON) || defined(__ARM_NEON__)
    {
        float32x4_t acc = vdupq_n_f32(0.0f);
        float32x4_t va_0 = vld1q_f32(a + 0);
        float32x4_t vb_0 = vld1q_f32(b + 0);
        acc = vfmaq_f32(acc, va_0, vb_0);
        float32x4_t va_1 = vld1q_f32(a + 4);
        float32x4_t vb_1 = vld1q_f32(b + 4);
        acc = vfmaq_f32(acc, va_1, vb_1);
        float tmp[4]; vst1q_f32(tmp, acc);
        result = tmp[0] + tmp[1] + tmp[2] + tmp[3];
    }
#else
    result += a[0] * b[0];
    result += a[1] * b[1];
    result += a[2] * b[2];
    result += a[3] * b[3];
    result += a[4] * b[4];
    result += a[5] * b[5];
    result += a[6] * b[6];
    result += a[7] * b[7];
#endif
    return result;
}

/* === Forward declarations === */
void rule_encode_v0(const float* query, float* out_shifted);
void rule_encode(const float* query, float* out_shifted);
void rule_main_v0(const float* query, int* out_best_idx);
void rule_main(const float* query, int* out_best_idx);

/* rule encode_v0 */
void rule_encode_v0(const float* query, float* out_shifted) {
    float ag[8] = {0};
    ag[0] = query[0] * concept_role_agent[0];
    ag[1] = query[1] * concept_role_agent[1];
    ag[2] = query[2] * concept_role_agent[2];
    ag[3] = query[3] * concept_role_agent[3];
    ag[4] = query[4] * concept_role_agent[4];
    ag[5] = query[5] * concept_role_agent[5];
    ag[6] = query[6] * concept_role_agent[6];
    ag[7] = query[7] * concept_role_agent[7];
    float ac[8] = {0};
    ac[0] = query[0] * concept_role_action[0];
    ac[1] = query[1] * concept_role_action[1];
    ac[2] = query[2] * concept_role_action[2];
    ac[3] = query[3] * concept_role_action[3];
    ac[4] = query[4] * concept_role_action[4];
    ac[5] = query[5] * concept_role_action[5];
    ac[6] = query[6] * concept_role_action[6];
    ac[7] = query[7] * concept_role_action[7];
    float paired[8] = {0};
    paired[0] = ag[0] + ac[0];
    paired[1] = ag[1] + ac[1];
    paired[2] = ag[2] + ac[2];
    paired[3] = ag[3] + ac[3];
    paired[4] = ag[4] + ac[4];
    paired[5] = ag[5] + ac[5];
    paired[6] = ag[6] + ac[6];
    paired[7] = ag[7] + ac[7];
    float __max_abs = 0.0f;
    if (paired[0] < 0.0f) { if (-paired[0] > __max_abs) __max_abs = -paired[0]; } else { if (paired[0] > __max_abs) __max_abs = paired[0]; }
    if (paired[1] < 0.0f) { if (-paired[1] > __max_abs) __max_abs = -paired[1]; } else { if (paired[1] > __max_abs) __max_abs = paired[1]; }
    if (paired[2] < 0.0f) { if (-paired[2] > __max_abs) __max_abs = -paired[2]; } else { if (paired[2] > __max_abs) __max_abs = paired[2]; }
    if (paired[3] < 0.0f) { if (-paired[3] > __max_abs) __max_abs = -paired[3]; } else { if (paired[3] > __max_abs) __max_abs = paired[3]; }
    if (paired[4] < 0.0f) { if (-paired[4] > __max_abs) __max_abs = -paired[4]; } else { if (paired[4] > __max_abs) __max_abs = paired[4]; }
    if (paired[5] < 0.0f) { if (-paired[5] > __max_abs) __max_abs = -paired[5]; } else { if (paired[5] > __max_abs) __max_abs = paired[5]; }
    if (paired[6] < 0.0f) { if (-paired[6] > __max_abs) __max_abs = -paired[6]; } else { if (paired[6] > __max_abs) __max_abs = paired[6]; }
    if (paired[7] < 0.0f) { if (-paired[7] > __max_abs) __max_abs = -paired[7]; } else { if (paired[7] > __max_abs) __max_abs = paired[7]; }
    if (__max_abs > 1e-9f) { for (int i = 0; i < 8; i++) paired[i] /= __max_abs; }
    float shifted[8] = {0};
    shifted[0] = paired[7];
    shifted[1] = paired[0];
    shifted[2] = paired[1];
    shifted[3] = paired[2];
    shifted[4] = paired[3];
    shifted[5] = paired[4];
    shifted[6] = paired[5];
    shifted[7] = paired[6];

    /* Outputs */
    for (int i = 0; i < 8; i++) out_shifted[i] = shifted[i];
}

/* dispatcher for rule encode (1 variant(s)) */
void rule_encode(const float* query, float* out_shifted) {
    rule_encode_v0(query, out_shifted);
    return;
    /* no variant matched: passthrough input */
    for (int i = 0; i < 8; i++) out_shifted[i] = query[i];
}

/* rule main_v0 */
void rule_main_v0(const float* query, int* out_best_idx) {
    float enc[8] = {0};
    rule_encode(query, enc);
    float best_score_0 = (enc[0] * alice__identity[0] + enc[1] * alice__identity[1] + enc[2] * alice__identity[2] + enc[3] * alice__identity[3] + enc[4] * alice__identity[4] + enc[5] * alice__identity[5] + enc[6] * alice__identity[6] + enc[7] * alice__identity[7]);  /* alice */
    float best_score_1 = (enc[0] * bob__identity[0] + enc[1] * bob__identity[1] + enc[2] * bob__identity[2] + enc[3] * bob__identity[3] + enc[4] * bob__identity[4] + enc[5] * bob__identity[5] + enc[6] * bob__identity[6] + enc[7] * bob__identity[7]);  /* bob */
    float best_score_2 = (enc[0] * carol__identity[0] + enc[1] * carol__identity[1] + enc[2] * carol__identity[2] + enc[3] * carol__identity[3] + enc[4] * carol__identity[4] + enc[5] * carol__identity[5] + enc[6] * carol__identity[6] + enc[7] * carol__identity[7]);  /* carol */
    *out_best_idx = 0;
    float __best = best_score_0;
    if (best_score_1 > __best) { __best = best_score_1; *out_best_idx = 1; }
    if (best_score_2 > __best) { __best = best_score_2; *out_best_idx = 2; }

    /* Outputs */
}

/* dispatcher for rule main (1 variant(s)) */
void rule_main(const float* query, int* out_best_idx) {
    rule_main_v0(query, out_best_idx);
    return;
    /* no variant matched: passthrough input */
    *out_best_idx = 0;
}

int main(int argc, char** argv) {
    float q[8];
    if (argc < 9) {
        fprintf(stderr, "usage: main v0 v1 ... v7\n");
        return 1;
    }
    for (int i = 0; i < 8; i++) q[i] = (float)atof(argv[i+1]);
    int out_best_idx = -1;
    rule_main(q, &out_best_idx);
    printf("%d\n", out_best_idx);
    return 0;
}
