#!/usr/bin/env python3
"""Generate LAL source for all 48 GPT-2 weight matrices (12 layers × 4 matrices).

Each layer has 4 weight matrices:
  - attn.c_attn   [768→2304]  (QKV projection)
  - attn.c_proj   [768→768]   (attention output projection)
  - mlp.c_fc      [768→3072]  (MLP up-projection)
  - mlp.c_proj    [3072→768]  (MLP down-projection)

Total: 12 × 4 = 48 binary linear layers.

The generated .lal file declares 48 relates, each loading a real GPT-2 weight
matrix and binarizing it. The C output provides 48 functions that the runtime
calls instead of float matmul.
"""
import os

def main():
    # Generate the 768-element bound
    dims = ", ".join(str(i) for i in range(768))

    lines = []
    lines.append("# gpt2_binary_layers.lal — ALL 48 GPT-2 weight matrices, binarized.")
    lines.append("# Generated by gen_gpt2_binary_layers.py")
    lines.append("# Each relate loads a REAL GPT-2 weight matrix and binarizes it to {-1,+1}.")
    lines.append("# The C output provides XNOR+popcount functions for 26.7x speedup.")
    lines.append("")
    lines.append(f"bound all_dims = [{dims}]")
    lines.append("")

    # 12 layers × 4 matrices
    for layer in range(12):
        for name, key, in_dim in [
            ("attn_qkv",   f"h.{layer}.attn.c_attn",   768),
            ("attn_proj",  f"h.{layer}.attn.c_proj",    768),
            ("mlp_fc",     f"h.{layer}.mlp.c_fc",       768),
            ("mlp_proj",   f"h.{layer}.mlp.c_proj",    3072),
        ]:
            fn_name = f"l{layer}_{name}"
            lines.append(f'relate {fn_name}(x) = linear(x, "gpt2_weights.bin", "{key}", threshold=0.0)')

    lines.append("")
    lines.append("# Dummy entry rule (the runtime calls the individual relates directly)")
    lines.append("rule dummy(query):")
    lines.append("    h = l0_attn_qkv(query)")
    lines.append("    output(h)")

    out = "/home/z/my-project/scripts/lal/gpt2_binary_layers.lal"
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"[*] wrote {out} with 48 binary linear relates (12 layers × 4 matrices)")

if __name__ == "__main__":
    main()
