/*
 * Generated by lalc — the LAL compiler.
 *
 * Source rule: classify
 * Specializations applied at compile time:
 *   - BOUND: only used dimensions retained in concept vectors
 *   - DOT: fully unrolled, no loops
 *   - AND/OR/comparisons: inlined as arithmetic
 *   - argmax: flat comparison chain, no dispatch
 *   - No generic matmul, no runtime mask indirection
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* === Concept vectors (after BOUND applied at compile time) ===
 * Only (concept, bound) pairs actually referenced in the rule body are emitted.
 * Unused combinations are eliminated at compile time. */
static const float car__machine_dims[4] = {0.900000f, 0.800000f, 0.700000f, 0.600000f};
static const float cat__animal_dims[4] = {1.000000f, 0.200000f, 0.700000f, 0.800000f};
static const float dog__animal_dims[4] = {0.800000f, 0.300000f, 0.600000f, 0.700000f};
static const float vehicle__machine_dims[4] = {0.900000f, 0.900000f, 0.600000f, 0.700000f};

/* === Compiled rule: classify === */
/* Input: float q[8] (full-dim query vector) */
void classify(const float* q, int* out_best) {
    /* Apply BOUNDs to the input at compile-time-known indices */
    float q__animal_dims[4] = {q[0], q[2], q[3], q[6]};
    float q__machine_dims[4] = {q[1], q[2], q[4], q[7]};


    /* Outputs */
    float best_score_0 = (q__animal_dims[0] * cat__animal_dims[0] + q__animal_dims[1] * cat__animal_dims[1] + q__animal_dims[2] * cat__animal_dims[2] + q__animal_dims[3] * cat__animal_dims[3]);  /* cat */
    float best_score_1 = (q__animal_dims[0] * dog__animal_dims[0] + q__animal_dims[1] * dog__animal_dims[1] + q__animal_dims[2] * dog__animal_dims[2] + q__animal_dims[3] * dog__animal_dims[3]);  /* dog */
    float best_score_2 = (q__machine_dims[0] * car__machine_dims[0] + q__machine_dims[1] * car__machine_dims[1] + q__machine_dims[2] * car__machine_dims[2] + q__machine_dims[3] * car__machine_dims[3]);  /* car */
    float best_score_3 = (q__machine_dims[0] * vehicle__machine_dims[0] + q__machine_dims[1] * vehicle__machine_dims[1] + q__machine_dims[2] * vehicle__machine_dims[2] + q__machine_dims[3] * vehicle__machine_dims[3]);  /* vehicle */
    *out_best = 0;
    float __best = best_score_0;
    if (best_score_1 > __best) { __best = best_score_1; *out_best = 1; }
    if (best_score_2 > __best) { __best = best_score_2; *out_best = 2; }
    if (best_score_3 > __best) { __best = best_score_3; *out_best = 3; }
}

int main(int argc, char** argv) {
    float q[8];
    if (argc < 9) {
        fprintf(stderr, "usage: demo v0 v1 ... v7\n");
        return 1;
    }
    for (int i = 0; i < 8; i++) q[i] = (float)atof(argv[i+1]);
     int out_best = -1;
    classify(q, &out_best);
    printf("%d\n", out_best);
    return 0;
}
