#!/usr/bin/env python3
"""Analyze GPT-2 weights for logic-guided binarization.

Goal: identify which attention heads and MLP channels carry "core logic"
(high information content) vs "noise" (low information, can be pruned).

Metrics:
1. Per-head weight norm: heads with large norms carry more information
2. Per-head activation diversity: heads that fire on diverse inputs are core
3. Weight sign balance: heads with ~50% positive weights are "balanced" (good),
   heads with extreme imbalance (>90% positive) are "biased" (may be noise)
4. Inter-head correlation: highly correlated heads are redundant (can merge/prune)

Output: a logic_mask per layer that marks each weight as:
  - CORE (keep float, don't binarize)
  - BINARY (sign(w) + alpha, current approach)
  - PRUNE (zero out, not even binarized)
"""
import struct, sys, os
import numpy as np

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

FLOAT_PATH = os.path.join(REPO_ROOT, "prebuilt", "gpt2_weights.bin")

def load_gpw2(path):
    with open(path, "rb") as f:
        magic = f.read(4)
        assert magic == b"GPW2"
        n = struct.unpack("I", f.read(4))[0]
        tensors = {}
        for _ in range(n):
            klen = struct.unpack("I", f.read(4))[0]
            key = f.read(klen).decode("utf-8")
            ndim = struct.unpack("I", f.read(4))[0]
            shape = [struct.unpack("I", f.read(4))[0] for _ in range(ndim)]
            n_elem = 1
            for s in shape: n_elem *= s
            data = np.frombuffer(f.read(n_elem * 4), dtype=np.float32)
            tensors[key] = data.reshape(shape)
        return tensors

def analyze_head_importance(tensors, n_layer=12, n_head=12, n_embd=768):
    """Analyze per-head importance for logic-guided binarization."""
    head_dim = n_embd // n_head  # 64
    
    print("=== Per-head importance analysis ===\n")
    print(f"{'Layer':<6} {'Head':<5} {'Norm':<10} {'Pos%':<8} {'Balanced':<10} {'Verdict':<10}")
    print("-" * 55)
    
    all_heads = []
    
    for l in range(n_layer):
        # c_attn weight is [n_embd, 3*n_embd] = [768, 2304]
        # Q part: columns 0..767, K: 768..1535, V: 1536..2303
        W = tensors[f"h.{l}.attn.c_attn.weight"]  # [768, 2304]
        
        for h in range(n_head):
            # Q weights for this head: W[:, h*64:(h+1)*64]
            Q_h = W[:, h*head_dim:(h+1)*head_dim]  # [768, 64]
            
            norm = np.linalg.norm(Q_h)
            pos_frac = np.mean(Q_h > 0)
            balanced = 1.0 - abs(pos_frac - 0.5) * 2  # 1.0 at 50%, 0.0 at 0%/100%
            
            if balanced > 0.8 and norm > np.median(np.linalg.norm(W[:, :n_embd].reshape(n_embd, n_head, head_dim), axis=(0,2))):
                verdict = "CORE"
            elif balanced < 0.3 or norm < 0.3 * np.median(np.linalg.norm(W[:, :n_embd].reshape(n_embd, n_head, head_dim), axis=(0,2))):
                verdict = "PRUNE"
            else:
                verdict = "BINARY"
            
            all_heads.append((l, h, norm, pos_frac, balanced, verdict))
            if l < 2 or verdict == "CORE" or verdict == "PRUNE":
                print(f"{l:<6} {h:<5} {norm:<10.3f} {pos_frac:<8.3f} {balanced:<10.3f} {verdict:<10}")
    
    # Summary
    core = sum(1 for h in all_heads if h[5] == "CORE")
    binary = sum(1 for h in all_heads if h[5] == "BINARY")
    prune = sum(1 for h in all_heads if h[5] == "PRUNE")
    total = len(all_heads)
    
    print(f"\n=== Summary ===")
    print(f"Total heads: {total}")
    print(f"CORE (keep float): {core} ({core/total*100:.1f}%)")
    print(f"BINARY (sign+alpha): {binary} ({binary/total*100:.1f}%)")
    print(f"PRUNE (zero out): {prune} ({prune/total*100:.1f}%)")
    
    # Estimate memory impact
    # Each head's Q weights: 768*64 = 49152 floats = 192KB
    # CORE heads stay float: 192KB each
    # BINARY heads: 768*64/8 = 6KB each (sign bits)
    # PRUNE heads: 0
    core_mem = core * 768 * 64 * 4 / 1e6  # MB
    binary_mem = binary * 768 * 64 / 8 / 1e6  # MB
    prune_mem = 0
    total_mem = core_mem + binary_mem
    current_mem = total * 768 * 64 * 4 / 1e6  # all float
    
    print(f"\n=== Memory estimate (Q weights only, 12 layers) ===")
    print(f"Current (all float): {current_mem:.1f} MB")
    print(f"Logic-guided: CORE={core_mem:.1f}MB + BINARY={binary_mem:.1f}MB = {total_mem:.1f} MB")
    print(f"Compression: {current_mem/total_mem:.1f}x")
    
    # Generate logic_mask for bin_layer_init
    print(f"\n=== Logic mask (for runtime) ===")
    print(f"// Per-layer head verdicts (CORE=0, BINARY=1, PRUNE=2)")
    print(f"// Generated by scripts/analyze_logic_binarization.py")
    for l in range(n_layer):
        layer_heads = [(h[1], h[5]) for h in all_heads if h[0] == l]
        verdicts = []
        for h, v in layer_heads:
            if v == "CORE": verdicts.append("0")
            elif v == "BINARY": verdicts.append("1")
            else: verdicts.append("2")
        print(f"layer {l:2d}: [{', '.join(verdicts)}]")
    
    return all_heads

def analyze_mlp_channels(tensors, n_layer=12, n_embd=768, mlp_dim=3072):
    """Analyze MLP channel importance."""
    print("\n=== MLP channel analysis ===\n")
    
    for l in range(min(3, n_layer)):  # Just first 3 layers for demo
        W = tensors[f"h.{l}.mlp.c_fc.weight"]  # [768, 3072]
        norms = np.linalg.norm(W, axis=0)  # per-output-channel norm
        
        # Sort channels by norm
        sorted_idx = np.argsort(norms)
        
        bottom_10pct = norms[sorted_idx[:len(sorted_idx)//10]]
        top_10pct = norms[sorted_idx[-len(sorted_idx)//10:]]
        
        print(f"Layer {l}: norm range [{norms.min():.3f}, {norms.max():.3f}]")
        print(f"  Bottom 10%: mean={bottom_10pct.mean():.3f} (candidates for PRUNE)")
        print(f"  Top 10%: mean={top_10pct.mean():.3f} (candidates for CORE)")
        
        # Count near-zero channels (|norm| < 10% of max)
        threshold = 0.1 * norms.max()
        n_prune = np.sum(norms < threshold)
        print(f"  Channels with norm < {threshold:.3f} (10% of max): {n_prune}/{mlp_dim} ({n_prune/mlp_dim*100:.1f}%)")

if __name__ == "__main__":
    print("[*] Loading GPT-2 weights...")
    tensors = load_gpw2(FLOAT_PATH)
    print(f"[*] Loaded {len(tensors)} tensors\n")
    
    heads = analyze_head_importance(tensors)
    analyze_mlp_channels(tensors)
    
    print("\n=== Conclusion ===")
    print("Logic-guided binarization can:")
    print("1. Keep CORE heads as float (preserves key concept detection)")
    print("2. Binarize BINARY heads (saves memory, XNOR+popcount speed)")
    print("3. Prune PRUNE heads (saves memory, removes noise)")
    print("4. This is 'logic extraction at binarization time' — not post-hoc STE")
