#!/usr/bin/env python3
"""Generate scripts/qwen_train_data.h: pre-tokenize corpus.txt with the REAL
Qwen2-0.5B BPE tokenizer (HuggingFace transformers), emitting a C header in
the same format as scripts/train_data.h (for GPT-2).

This replaces the hardcoded fake tokens in models/qwen.c's encode() (which
returned 1..7) with real Qwen BPE ids, so Qwen training runs on real data —
mirroring how models/gpt2.c consumes scripts/train_data.h.

Usage:  python3 scripts/gen_qwen_train_data.py
Output: scripts/qwen_train_data.h
"""
import os
import sys

CORPUS = os.path.join(os.path.dirname(__file__), "corpus.txt")
OUT    = os.path.join(os.path.dirname(__file__), "qwen_train_data.h")
MAX_TOK = 32
MIN_TOK = 4
MODEL_NAME = os.environ.get("QWEN_MODEL", "Qwen/Qwen2-0.5B")
# Prefer a local tokenizer.json (downloaded from hf-mirror.com) to avoid HF
# Hub connectivity flakiness in sandboxes. Fall back to transformers otherwise.
LOCAL_TOK = os.environ.get("QWEN_TOKENIZER_JSON", os.path.join(os.path.dirname(__file__), "..", "prebuilt", "qwen_tokenizer.json"))

def load_corpus(path):
    sents = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            sents.append(line)
    return sents

def main():
    tok = None
    if os.path.isfile(LOCAL_TOK):
        try:
            from tokenizers import Tokenizer
            print(f"[*] loading local tokenizer {LOCAL_TOK} ...")
            tok = Tokenizer.from_file(LOCAL_TOK)
            print(f"[*] vocab_size={tok.get_vocab_size()}")
        except Exception as e:
            print(f"[!] local tokenizer load failed: {e}; falling back to transformers")
            tok = None
    if tok is None:
        try:
            from transformers import AutoTokenizer
        except ImportError:
            sys.exit("ERROR: need transformers or a local qwen_tokenizer.json (tokenizers lib)")
        print(f"[*] loading tokenizer {MODEL_NAME} ...")
        tok = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)
        print(f"[*] vocab_size={tok.vocab_size}  (model_max_len={tok.model_max_length})")
        def _enc(s):
            return tok(s, add_special_tokens=False)["input_ids"]
    else:
        def _enc(s):
            return tok.encode(s).ids

    sents = load_corpus(CORPUS)
    print(f"[*] corpus: {len(sents)} non-comment lines")

    rows = []
    skipped = 0
    for s in sents:
        ids = _enc(s)
        if len(ids) < MIN_TOK or len(ids) > MAX_TOK:
            skipped += 1
            continue
        rows.append((ids, s))

    print(f"[*] kept {len(rows)} sentences ({skipped} out of token range "
          f"[{MIN_TOK},{MAX_TOK}])")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by scripts/gen_qwen_train_data.py — do not edit.\n")
        f.write(f" * Pre-tokenized training corpus for Qwen (models/qwen.c).\n")
        f.write(f" * Source: scripts/corpus.txt  Tokenizer: {MODEL_NAME} (BPE)\n")
        f.write(f" * Each entry: {{ int ids[{MAX_TOK}]; int n; }}  (n = token count, <= {MAX_TOK})\n")
        f.write(f" * Consume in qwen.c:\n")
        f.write(f" *   #include \"qwen_train_data.h\"\n")
        f.write(f" *   for (i=0; i<N_TRAIN; i++) train_one(&train_data[i]);\n")
        f.write(f" */\n")
        f.write("#ifndef QWEN_TRAIN_DATA_H\n#define QWEN_TRAIN_DATA_H\n\n")
        f.write(f"#define MAX_TOK {MAX_TOK}\n")
        f.write(f"#define N_TRAIN {len(rows)}\n")
        f.write(f"static const struct {{ int ids[{MAX_TOK}]; int n; }} train_data[N_TRAIN] = {{\n")
        for ids, s in rows:
            arr = ",".join(str(i) for i in ids)
            # include a truncated comment of the source sentence
            cmt = (s[:44] + "...") if len(s) > 47 else s
            f.write(f'  {{ {{ {arr} }}, {len(ids)} }},  /* {cmt} */\n')
        f.write("};\n#endif\n")
    print(f"[*] wrote {OUT}  ({len(rows)} entries)")

if __name__ == "__main__":
    main()
