/* Auto-generated by scripts/gen_qwen_train_data.py — do not edit.
 * Pre-tokenized training corpus for Qwen (models/qwen.c).
 * Source: scripts/corpus.txt  Tokenizer: Qwen/Qwen2-0.5B (BPE)
 * Each entry: { int ids[32]; int n; }  (n = token count, <= 32)
 * Consume in qwen.c:
 *   #include "qwen_train_data.h"
 *   for (i=0; i<N_TRAIN; i++) train_one(&train_data[i]);
 */
#ifndef QWEN_TRAIN_DATA_H
#define QWEN_TRAIN_DATA_H

#define MAX_TOK 32
#define N_TRAIN 370
static const struct { int ids[32]; int n; } train_data[N_TRAIN] = {
  { { 785,6722,315,9625,374,12095,323,432,374,264,6233,3283,13 }, 13 },  /* The capital of France is Paris and it is a b... */
  { { 785,6722,315,6323,374,26194,892,374,264,1602,13028,1992,13 }, 13 },  /* The capital of Japan is Tokyo which is a ver... */
  { { 785,6722,315,9856,374,19846,323,279,1251,525,11657,13 }, 12 },  /* The capital of Germany is Berlin and the peo... */
  { { 785,6722,315,15344,374,21718,323,279,3607,374,11117,1052,13 }, 13 },  /* The capital of Italy is Rome and the food is... */
  { { 785,6722,315,17689,374,24081,323,279,9104,374,3545,8205,13 }, 13 },  /* The capital of Spain is Madrid and the weath... */
  { { 785,6722,315,8359,374,22415,323,84982,525,1602,9255,13 }, 12 },  /* The capital of Russia is Moscow and winters ... */
  { { 785,6722,315,5616,374,26549,323,432,702,264,1293,3840,13 }, 13 },  /* The capital of China is Beijing and it has a... */
  { { 785,6722,315,6747,374,1532,21996,323,279,14371,525,38213,13 }, 13 },  /* The capital of India is New Delhi and the st... */
  { { 785,6722,315,15948,374,61124,24078,537,26961,409,60323,13 }, 12 },  /* The capital of Brazil is Brasilia not Rio de... */
  { { 785,6722,315,14867,374,52550,323,279,14796,76190,27455,1526,432,13 }, 14 },  /* The capital of Egypt is Cairo and the river ... */
  { { 28253,88955,518,825,7739,12348,61347,518,9396,2188,13 }, 11 },  /* Water boils at one hundred degrees Celsius a... */
  { { 785,9237,5780,2163,279,8059,3055,1449,1042,13 }, 10 },  /* The Earth goes around the Sun once every year. */
  { { 13911,34192,1602,4937,714,5112,34192,1753,803,13970,13 }, 11 },  /* Light travels very fast but sound travels mu... */
  { { 2120,1783,990,39020,311,1281,862,1828,3607,304,862,10901,13 }, 13 },  /* Plants use sunlight to make their own food i... */
  { { 785,3738,2487,702,1378,7739,323,4743,24854,304,2790,13 }, 12 },  /* The human body has two hundred and six bones... */
  { { 32,32197,702,1378,10335,2598,279,10200,323,9806,50779,13 }, 12 },  /* A magnet has two ends called the north and s... */
  { { 46,18936,374,264,6819,429,582,1184,311,36297,311,4717,13675,13 }, 14 },  /* Oxygen is a gas that we need to breathe to s... */
  { { 785,17330,11137,279,259,3341,304,279,53180,315,279,9237,13 }, 13 },  /* The Moon causes the tides in the oceans of t... */
  { { 32,47613,7952,304,279,12884,1283,279,11174,389,264,39698,1899,13 }, 14 },  /* A rainbow appears in the sky after the rain ... */
  { { 79071,1896,304,12499,39489,323,2968,700,23552,369,601,13 }, 12 },  /* Trees take in carbon dioxide and give out ox... */
  { { 785,13833,81504,5798,3460,4510,86373,438,10180,1279,369,44519,13 }, 13 },  /* The ancient Egyptians built large pyramids a... */
  { { 49,635,572,264,2244,31347,429,21286,1753,315,4505,1293,4134,13 }, 14 },  /* Rome was a great empire that ruled much of E... */
  { { 785,18484,3493,572,35492,311,1281,6467,1753,23048,13 }, 11 },  /* The printing press was invented to make book... */
  { { 785,13284,572,35492,1657,9037,315,1635,1573,9331,13 }, 11 },  /* The wheel was invented many thousands of yea... */
  { { 42,819,323,68997,12163,304,6311,642,448,1550,14285,323,4544,1862,13 }, 15 },  /* Kings and queens lived in castles with high ... */
  { { 50,604,1087,1483,279,9759,311,1477,862,1616,3941,279,53180,13 }, 14 },  /* Sailors used the stars to find their way acr... */
  { { 785,1156,18495,1033,1602,3460,323,10199,4361,12026,13 }, 11 },  /* The first computers were very large and fill... */
  { { 15919,3055,79169,9898,448,2341,1561,1865,315,7579,323,9798,13 }, 13 },  /* People once hunted animals with spears made ... */
  { { 39173,11291,11691,39944,323,48559,1948,28727,11835,13 }, 10 },  /* Trade routes carried silk and spices between... */
  { { 18284,85469,2115,4815,56897,323,42322,369,601,311,1349,13 }, 12 },  /* Old civilizations left behind temples and wr... */
  { { 40,1075,311,7027,264,10525,315,10799,304,279,4124,6556,13 }, 13 },  /* I like to drink a cup of coffee in the early... */
  { { 7941,3937,311,279,3081,311,3695,7722,13779,323,23880,13 }, 12 },  /* She went to the market to buy fresh fruit an... */
  { { 785,2841,6342,304,279,6118,3080,279,7015,3937,1495,13 }, 12 },  /* The children played in the park until the su... */
  { { 1519,8356,279,10865,10496,448,264,23457,323,1045,39843,13 }, 12 },  /* He fixed the broken chair with a hammer and ... */
  { { 1654,1030,13856,3786,323,14897,911,1039,1899,518,975,13 }, 12 },  /* We had dinner together and talked about our ... */
  { { 785,5828,572,3309,773,358,1030,311,3783,304,279,9255,11174,13 }, 14 },  /* The bus was late so I had to wait in the col... */
  { { 5050,38184,1865,19174,448,16158,323,19653,369,601,13 }, 11 },  /* My grandmother made soup with chicken and ri... */
  { { 785,5562,10613,311,279,6006,979,432,6617,1181,6372,5001,2114,13 }, 14 },  /* The dog ran to the door when it heard its ow... */
  { { 40,5558,847,6894,323,1030,311,2711,279,4361,3753,369,1105,13 }, 14 },  /* I lost my keys and had to search the whole h... */
  { { 6865,23983,279,14285,264,8413,6303,1894,311,1281,432,19300,13 }, 13 },  /* They painted the walls a soft blue color to ... */
  { { 12522,5193,264,882,1052,572,264,25079,553,279,9396,13 }, 12 },  /* Once upon a time there was a kingdom by the ... */
  { { 12522,5193,264,882,264,2613,25105,12163,389,264,16217,16301,13 }, 13 },  /* Once upon a time a small dragon lived on a t... */
  { { 12522,5193,264,882,264,7852,36400,1730,264,8968,315,6623,13 }, 13 },  /* Once upon a time a poor farmer found a bag o... */
  { { 12522,5193,264,882,264,27699,38835,14068,291,264,45237,9276,13 }, 13 },  /* Once upon a time a clever fox tricked a fool... */
  { { 12522,5193,264,882,264,3908,3743,30696,3041,311,5931,1059,32315,13 }, 14 },  /* Once upon a time a young girl traveled far t... */
  { { 12522,5193,264,882,264,11477,1030,2326,25350,879,1410,537,7503,13 }, 14 },  /* Once upon a time a king had three sons who c... */
  { { 12522,5193,264,882,264,23335,2310,883,12163,5538,304,279,13638,13 }, 14 },  /* Once upon a time a wise old man lived deep i... */
  { { 12522,5193,264,882,264,46609,738,700,311,1739,352,264,17478,31136,13 }, 15 },  /* Once upon a time a knight set out to slay a ... */
  { { 12522,5193,264,882,264,29238,75744,311,264,28727,4268,369,41686,13 }, 14 },  /* Once upon a time a merchant sailed to a dist... */
  { { 12522,5193,264,882,264,90378,8171,38069,36542,979,1052,572,6857,13 }, 14 },  /* Once upon a time a shepherd boy cried wolf w... */
  { { 21605,6832,374,264,25993,315,20443,11229,3351,13 }, 10 },  /* Machine learning is a subset of artificial i... */
  { { 32,6366,10533,821,389,264,13364,476,304,1181,4938,23595,13 }, 13 },  /* A computer stores data on a disk or in its m... */
  { { 785,7602,33061,18495,678,2163,279,4361,1879,13 }, 10 },  /* The internet connects computers all around t... */
  { { 32,20544,15354,1378,1251,3061,1496,979,3041,10747,13 }, 11 },  /* A telephone lets two people talk even when f... */
  { { 78828,614,21106,429,8231,10416,311,1281,1105,3271,4637,13 }, 12 },  /* Cars have engines that burn fuel to make the... */
  { { 32,6249,4990,264,6802,553,20194,3100,4399,389,264,12002,13 }, 13 },  /* A camera takes a picture by letting light fa... */
  { { 14465,2412,646,653,27759,476,11406,6887,369,3738,7337,13 }, 12 },  /* Robots can do boring or dangerous jobs for h... */
  { { 64865,487,27455,1526,35008,311,2355,1039,12711,323,7611,13 }, 12 },  /* Electricity flows through wires to power our... */
  { { 32,8866,5711,53160,476,47373,311,2506,3754,315,279,882,13 }, 13 },  /* A clock uses gears or crystals to keep track... */
  { { 19250,374,279,738,315,11221,429,10742,11773,1128,311,653,13 }, 13 },  /* Software is the set of instructions that tel... */
  { { 785,9104,3351,374,39698,323,8205,448,264,21700,45285,13 }, 12 },  /* The weather today is sunny and warm with a g... */
  { { 641,12406,279,11794,17066,323,279,43136,29930,916,2588,13 }, 12 },  /* In winter the snow falls and the lakes freez... */
  { { 25150,12434,501,19281,323,279,19654,470,311,7780,13 }, 11 },  /* Spring brings new flowers and the birds retu... */
  { { 50687,374,4017,323,279,2849,525,1293,323,9906,13 }, 11 },  /* Summer is hot and the days are long and bright. */
  { { 19602,21371,10901,2484,2518,323,6623,1573,807,4399,311,279,4910,13 }, 14 },  /* Autumn leaves turn red and gold before they ... */
  { { 32,13458,12434,36843,323,32438,323,8811,11174,13 }, 10 },  /* A storm brings thunder and lightning and hea... */
  { { 785,9956,41323,2588,678,3729,323,14422,264,4916,8870,13 }, 12 },  /* The wind blew hard all night and broke a tre... */
  { { 37,538,9761,279,33581,773,582,1410,537,1490,1602,3041,8305,13 }, 14 },  /* Fog covered the valley so we could not see v... */
  { { 6025,279,11174,279,3720,85698,7722,323,4240,323,10226,13 }, 12 },  /* After the rain the air smelled fresh and cle... */
  { { 785,17595,1053,432,1035,387,73549,714,432,1521,537,11174,13 }, 13 },  /* The forecast said it would be cloudy but it ... */
  { { 785,3974,13876,38835,34208,916,279,15678,5562,304,279,19515,13 }, 13 },  /* The quick brown fox jumps over the lazy dog ... */
  { { 32,8251,646,1490,304,279,6319,1753,2664,1091,264,3738,646,13 }, 14 },  /* A cat can see in the dark much better than a... */
  { { 39,22434,525,3746,9898,429,646,1598,1602,4937,12824,13 }, 12 },  /* Horses are strong animals that can run very ... */
  { { 64541,3887,304,3015,323,36297,1526,342,3305,389,862,11067,13 }, 13 },  /* Fish live in water and breathe through gills... */
  { { 65270,82,614,41802,24854,773,807,525,3100,3322,311,11466,13 }, 13 },  /* Birds have hollow bones so they are light en... */
  { { 32,11722,71390,1526,279,4361,12406,304,264,6319,25385,13 }, 12 },  /* A bear sleeps through the whole winter in a ... */
  { { 3430,288,1281,25744,504,279,308,38816,807,1477,304,279,19281,13 }, 14 },  /* Bees make honey from the nectar they find in... */
  { { 43,908,3887,304,5203,2598,548,3341,389,279,1787,16359,1933,13 }, 14 },  /* Lions live in groups called prides on the op... */
  { { 45339,52567,525,279,7772,9898,429,4227,389,279,4268,13 }, 12 },  /* Elephants are the largest animals that walk ... */
  { { 20720,2050,653,537,614,14201,714,807,3271,1602,6157,13 }, 12 },  /* Snakes do not have legs but they move very q... */
  { { 33,878,374,1865,504,19828,323,3015,323,40480,323,12021,13 }, 13 },  /* Bread is made from flour and water and yeast... */
  { { 1249,1281,15243,498,4914,4017,3015,916,279,10901,323,3783,13 }, 13 },  /* To make tea you pour hot water over the leav... */
  { { 26843,2367,374,1865,504,14074,323,646,12656,17232,476,23034,13 }, 13 },  /* Cheese is made from milk and can taste sharp... */
  { { 49,558,374,264,4185,3607,304,1657,5837,2163,279,1879,13 }, 13 },  /* Rice is a common food in many countries arou... */
  { { 32,1661,19174,1643,22780,13970,369,4115,389,279,44015,13 }, 12 },  /* A good soup simmers slowly for hours on the ... */
  { { 2164,642,3063,389,12408,323,646,387,2518,476,6176,476,13753,13 }, 14 },  /* Apples grow on trees and can be red or green... */
  { { 82280,26896,525,53562,1573,807,525,4910,323,88095,13 }, 11 },  /* Coffee beans are roasted before they are gro... */
  { { 36,70,5857,646,387,65085,476,40851,476,70478,369,17496,13 }, 13 },  /* Eggs can be boiled or fried or scrambled for... */
  { { 83414,3643,3607,10226,714,2238,1753,315,432,374,537,9314,13 }, 13 },  /* Sugar makes food sweet but too much of it is... */
  { { 47318,12434,700,279,17172,315,4558,1449,12000,582,4296,13 }, 12 },  /* Salt brings out the flavor of almost every d... */
  { { 785,4746,42775,6543,1526,279,2487,678,1899,323,3729,13 }, 12 },  /* The heart pumps blood through the body all d... */
  { { 1654,990,1039,6414,311,1490,323,1039,24230,311,6723,279,1879,13 }, 14 },  /* We use our eyes to see and our ears to hear ... */
  { { 24959,287,697,17832,13598,1105,4240,323,3746,323,4158,13 }, 12 },  /* Brushing your teeth keeps them clean and str... */
  { { 41745,8609,279,2487,2732,323,279,3971,6099,2513,1632,13 }, 12 },  /* Sleep helps the body rest and the mind remem... */
  { { 54,19049,697,6078,17933,17239,1011,504,3259,498,2666,14036,13 }, 13 },  /* Washing your hands stops germs from making y... */
  { { 785,8109,374,279,2872,429,15354,601,1744,323,3960,323,2666,13 }, 14 },  /* The brain is the organ that lets us think an... */
  { { 61598,18638,633,16245,979,498,990,1105,304,10158,3545,13 }, 12 },  /* Muscles get stronger when you use them in ex... */
  { { 33,3154,2968,279,2487,1181,6083,323,6016,279,8413,5479,13 }, 13 },  /* Bones give the body its shape and protect th... */
  { { 26746,6696,601,279,4802,582,1184,311,3271,323,311,3063,13 }, 13 },  /* Food gives us the energy we need to move and... */
  { { 8847,15736,3322,3015,374,2989,311,4717,9314,323,5115,13 }, 12 },  /* Drinking enough water is important to stay h... */
  { { 785,5426,11465,518,279,8056,1101,1573,11627,297,8866,13 }, 12 },  /* The train arrived at the station just before... */
  { { 1654,19375,1039,17899,323,23108,311,279,23501,369,279,9001,13 }, 13 },  /* We packed our bags and drove to the mountain... */
  { { 785,9500,3054,1030,264,1651,315,279,9396,323,279,6243,7015,13 }, 14 },  /* The hotel room had a view of the sea and the... */
  { { 32,2415,8609,498,1477,697,1616,979,498,525,304,264,501,1992,13 }, 15 },  /* A map helps you find your way when you are i... */
  { { 785,16733,572,38213,448,1251,2087,311,1657,9720,13 }, 11 },  /* The airport was crowded with people going to... */
  { { 7941,10788,264,11727,323,29215,389,279,5339,369,279,5426,13 }, 13 },  /* She bought a ticket and waited on the platfo... */
  { { 785,5636,26555,705,279,23946,1526,264,27950,6176,13638,13 }, 12 },  /* The road wound up the hill through a dense g... */
  { { 6865,3867,264,15328,3941,279,21800,311,5545,279,2613,12922,13 }, 13 },  /* They took a boat across the lake to reach th... */
  { { 785,23971,572,2480,315,2310,35592,323,14888,6171,13 }, 11 },  /* The museum was full of old paintings and str... */
  { { 32,8474,8542,601,2163,279,45662,323,3229,601,862,3364,13 }, 13 },  /* A guide showed us around the ruins and told ... */
  { { 785,11079,6139,279,17755,389,279,4479,369,279,536,13 }, 12 },  /* The teacher wrote the lesson on the board fo... */
  { { 1519,7822,2588,1449,3729,773,566,646,1494,279,7006,13 }, 12 },  /* He studies hard every night so he can pass t... */
  { { 785,8633,3643,15294,429,525,6088,304,1657,19456,13 }, 11 },  /* The factory makes shoes that are sold in man... */
  { { 7941,4278,518,264,8777,1380,1340,8609,14036,1251,13 }, 11 },  /* She works at a hospital where she helps sick... */
  { { 785,6438,3855,3309,1576,279,13392,572,15700,304,9442,13 }, 12 },  /* The meeting started late because the boss wa... */
  { { 30952,9226,862,6078,311,2548,279,11079,264,3405,13 }, 11 },  /* Students raised their hands to ask the teach... */
  { { 785,8061,15885,518,11627,323,33250,518,4743,304,279,11458,13 }, 13 },  /* The shop opens at nine and closes at six in ... */
  { { 32,36400,61567,4124,311,5395,279,9898,1573,279,38393,13 }, 12 },  /* A farmer wakes early to feed the animals bef... */
  { { 785,2083,6439,3786,311,6248,279,2390,389,882,13 }, 11 },  /* The team worked together to finish the proje... */
  { { 785,5163,572,11340,1576,5019,1030,8048,2114,2669,13 }, 11 },  /* The office was quiet because everyone had go... */
  { { 3862,525,52374,6486,304,264,9383,323,52374,4420,304,458,6460,13 }, 14 },  /* There are sixty seconds in a minute and sixt... */
  { { 59528,2849,1281,264,2003,323,32417,1378,5555,1281,264,1042,13 }, 13 },  /* Seven days make a week and fifty two weeks m... */
  { { 32,20403,3363,29235,315,2494,1075,18805,476,1513,6128,13 }, 12 },  /* A dozen means twelve of something like eggs ... */
  { { 785,8866,389,279,7002,8542,429,432,572,4279,3267,5779,13 }, 13 },  /* The clock on the wall showed that it was hal... */
  { { 32,9294,374,825,7739,1635,1293,438,582,1760,279,882,13 }, 13 },  /* A century is one hundred years long as we co... */
  { { 32146,702,26127,825,2849,1101,1075,5768,323,6156,653,13 }, 12 },  /* December has thirty one days just like July ... */
  { { 2132,4990,279,9237,17073,3040,4115,311,12616,2163,3055,13 }, 12 },  /* It takes the Earth twenty four hours to spin... */
  { { 785,1372,7168,572,264,1602,2989,4522,304,37596,13 }, 11 },  /* The number zero was a very important idea in... */
  { { 32,31471,1042,4041,1449,3040,1635,323,702,458,4960,1899,13 }, 13 },  /* A leap year comes every four years and has a... */
  { { 785,13168,8609,601,2506,3754,315,279,2849,323,279,3951,13 }, 13 },  /* The calendar helps us keep track of the days... */
  { { 7941,572,6247,979,1059,4238,3697,311,3947,1059,518,2114,13 }, 13 },  /* She was happy when her friend came to visit ... */
  { { 1519,6476,12421,979,806,2310,5562,1030,311,728,311,279,23313,13 }, 14 },  /* He felt sad when his old dog had to go to th... */
  { { 32,1661,4238,63648,979,498,614,2494,311,1977,13 }, 11 },  /* A good friend listens when you have somethin... */
  { { 6865,31527,3786,518,279,15173,21646,279,68468,3229,13 }, 11 },  /* They laughed together at the funny joke the ... */
  { { 785,1682,572,16575,315,279,6319,773,566,2115,264,3100,389,13 }, 14 },  /* The child was afraid of the dark so he left ... */
  { { 2132,374,3093,311,1492,4325,879,702,20866,389,279,4910,13 }, 13 },  /* It is kind to help someone who has fallen on... */
  { { 33535,2249,264,4238,1283,264,4367,3643,279,26509,3746,13 }, 12 },  /* Forgiving a friend after a fight makes the f... */
  { { 785,41189,572,773,12035,429,1181,4361,9787,1410,537,2936,13 }, 13 },  /* The puppy was so excited that its whole tail... */
  { { 32,15289,646,1281,264,3873,1899,2666,264,2632,2699,2664,13 }, 13 },  /* A smile can make a bad day feel a little bit... */
  { { 33142,10745,448,1251,22111,6950,916,264,1293,882,13 }, 11 },  /* Being honest with people builds trust over a... */
  { { 32,32861,304,882,25935,11627,438,279,2310,5488,5780,13 }, 12 },  /* A stitch in time saves nine as the old sayin... */
  { { 10380,1573,498,31471,773,498,653,537,4399,1119,264,22862,13 }, 13 },  /* Look before you leap so you do not fall into... */
  { { 5404,537,11651,264,2311,553,279,3421,429,498,1156,1490,13 }, 13 },  /* Do not judge a book by the cover that you fi... */
  { { 58289,323,24020,14816,279,6957,304,279,11245,2310,23281,13 }, 12 },  /* Slow and steady wins the race in the famous ... */
  { { 2082,23268,264,1899,13598,279,10668,3123,432,374,3545,1053,13 }, 13 },  /* An apple a day keeps the doctor away it is o... */
  { { 9064,1052,374,16205,1052,374,5990,264,3940,3265,553,13 }, 12 },  /* Where there is smoke there is usually a fire... */
  { { 785,4124,11958,37834,279,34211,438,279,78438,10742,601,13 }, 12 },  /* The early bird catches the worm as the prove... */
  { { 31246,1657,72427,64793,279,44893,979,5019,6801,2524,13 }, 11 },  /* Too many cooks spoil the broth when everyone... */
  { { 32,11618,315,264,16183,8756,12033,448,825,2613,3019,13 }, 12 },  /* A journey of a thousand miles begins with on... */
  { { 12948,6468,61796,1091,4244,429,1251,3545,1977,13 }, 10 },  /* Actions speak louder than words that people ... */
  { { 7941,22352,291,264,8511,504,27292,1340,10788,518,279,8061,13 }, 13 },  /* She sewed a dress from cloth she bought at t... */
  { { 1519,48167,264,22360,45505,504,264,6573,315,2310,37871,13 }, 12 },  /* He carved a wooden spoon from a piece of old... */
  { { 785,3338,465,26271,279,36048,1119,264,4778,323,16217,29595,13 }, 13 },  /* The potter shaped the clay into a round and ... */
  { { 6865,5798,264,2613,3753,504,49037,323,3746,23613,13 }, 11 },  /* They built a small house from bricks and str... */
  { { 32,3691,33017,76562,11001,3080,432,374,2518,323,1221,566,22368,13 }, 14 },  /* A blacksmith heats iron until it is red and ... */
  { { 1654,47035,5567,1119,1560,14655,311,56581,279,3054,369,279,4614,13 }, 14 },  /* We folded paper into cranes to decorate the ... */
  { { 785,21881,798,38341,19056,304,6978,3941,279,6319,17171,13 }, 12 },  /* The gardener planted seeds in rows across th... */
  { { 7941,289,994,264,14024,504,15430,29922,315,686,363,8870,13 }, 13 },  /* She wove a basket from thin strips of willow... */
  { { 1519,32419,279,16986,3080,1449,914,34308,1101,1290,13 }, 11 },  /* He tuned the guitar until every string sound... */
  { { 785,29481,9519,7987,389,279,4479,311,633,279,1290,27501,13 }, 13 },  /* The painter mixed colors on the board to get... */
  { { 785,7055,6342,264,5492,429,1865,5019,1366,311,15254,13 }, 12 },  /* The band played a song that made everyone wa... */
  { { 7941,28240,264,8413,25240,1393,1340,6439,304,279,9780,13 }, 12 },  /* She sang a soft tune while she worked in the... */
  { { 32,26278,702,3691,323,4158,6894,429,498,3493,311,1486,13 }, 13 },  /* A piano has black and white keys that you pr... */
  { { 785,62037,3643,264,1550,10226,5112,979,279,15273,374,14764,13 }, 13 },  /* The violin makes a high sweet sound when the... */
  { { 8847,6237,2506,279,9382,429,279,1008,23316,1795,13 }, 11 },  /* Drums keep the beat that the other instrumen... */
  { { 1519,23554,264,6802,315,279,16301,448,264,46118,323,5567,13 }, 13 },  /* He drew a picture of the mountain with a pen... */
  { { 785,70608,28240,3786,304,25281,518,279,7270,2473,13 }, 11 },  /* The choir sang together in harmony at the Su... */
  { { 32,95712,374,264,1293,15430,13705,448,19766,3156,1181,3108,13 }, 13 },  /* A flute is a long thin tube with holes along... */
  { { 785,10049,23983,279,12884,304,36099,315,18217,323,6623,13 }, 12 },  /* The artist painted the sky in shades of pink... */
  { { 24128,646,1281,601,2666,15888,476,57496,2041,894,4244,13 }, 12 },  /* Music can make us feel joy or sorrow without... */
  { { 785,4628,315,3100,374,911,220,18,15,15,3526,20044,817,2086,304,264,28202,13 }, 18 },  /* The speed of light is about 300 million mete... */
  { { 55320,5610,279,18929,11221,369,678,5382,43204,13 }, 10 },  /* DNA contains the genetic instructions for al... */
  { { 785,3738,8109,49442,911,220,16,13,19,84302,323,702,220,23,21,7094,33213,13 }, 18 },  /* The human brain weighs about 1.4 kilograms a... */
  { { 31772,73667,32722,39020,1119,11483,4802,304,10779,13 }, 10 },  /* Photosynthesis converts sunlight into chemic... */
  { { 785,9237,594,16566,374,10008,46403,323,23552,13 }, 10 },  /* The Earth's atmosphere is mostly nitrogen an... */
  { { 28253,93377,518,7168,12348,61347,323,88955,518,825,7739,12348,13 }, 13 },  /* Water freezes at zero degrees Celsius and bo... */
  { { 38409,13598,279,17330,304,26507,2163,279,9237,13 }, 10 },  /* Gravity keeps the Moon in orbit around the E... */
  { { 64865,487,27455,1526,6786,1087,1075,23285,323,6623,13 }, 11 },  /* Electricity flows through conductors like co... */
  { { 785,38345,1965,2872,4756,5424,553,862,24510,1372,13 }, 11 },  /* The periodic table organizes elements by the... */
  { { 91303,6685,315,462,34411,25793,25610,323,56578,13 }, 10 },  /* Atoms consist of protons neutrons and electr... */
  { { 785,10126,315,1351,43415,572,10981,553,17513,54052,13 }, 11 },  /* The theory of relativity was proposed by Alb... */
  { { 16103,34192,10596,304,3015,1091,304,3720,13 }, 9 },  /* Sound travels faster in water than in air. */
  { { 32,47613,7586,979,39020,16211,1526,11174,90512,13 }, 10 },  /* A rainbow forms when sunlight passes through... */
  { { 785,8059,374,264,6774,518,279,4126,315,1039,12941,1849,13 }, 13 },  /* The Sun is a star at the center of our solar... */
  { { 36361,4814,7072,43679,979,63505,37168,504,5538,25260,13 }, 11 },  /* Volcanoes erupt when magma rises from deep u... */
  { { 785,8513,9736,315,5616,572,5798,916,1657,23631,13 }, 11 },  /* The Great Wall of China was built over many ... */
  { { 88067,1167,81504,5798,4510,86373,438,10180,1279,369,862,1319,81197,82,13 }, 15 },  /* Ancient Egyptians built pyramids as tombs fo... */
  { { 785,12751,20448,11052,304,279,1042,220,19,22,21,9630,13 }, 13 },  /* The Roman Empire fell in the year 476 AD. */
  { { 10134,5004,9043,9482,304,220,16,24,19,20,448,279,31759,315,6323,13 }, 16 },  /* World War Two ended in 1945 with the surrend... */
  { { 785,18484,3493,572,35492,553,54105,51586,13 }, 9 },  /* The printing press was invented by Johannes ... */
  { { 73966,31817,8643,279,51148,304,220,16,19,24,17,13 }, 12 },  /* Christopher Columbus reached the Americas in... */
  { { 785,8585,22126,3855,304,220,16,22,23,24,323,5497,4505,15683,13 }, 15 },  /* The French Revolution started in 1789 and ch... */
  { { 785,24545,22126,6009,304,13224,304,279,220,16,23,339,9294,13 }, 14 },  /* The Industrial Revolution began in Britain i... */
  { { 85384,72771,30696,504,4505,311,5616,3156,279,51036,9536,13 }, 12 },  /* Marco Polo traveled from Europe to China alo... */
  { { 785,19846,9736,572,21145,1495,304,220,16,24,23,24,13391,279,23185,5004,13 }, 17 },  /* The Berlin Wall was torn down in 1989 ending... */
  { { 785,8176,10948,374,279,22032,14796,304,4882,5159,13 }, 11 },  /* The Amazon River is the longest river in Sou... */
  { { 16284,86478,374,279,8426,16301,304,279,1879,13 }, 10 },  /* Mount Everest is the highest mountain in the... */
  { { 785,87978,42186,14521,1753,315,18172,10174,13 }, 9 },  /* The Sahara Desert covers much of northern Af... */
  { { 48037,374,2176,264,3146,323,264,31743,13 }, 9 },  /* Australia is both a country and a continent. */
  { { 785,16462,21575,374,279,7772,17951,389,9237,13 }, 10 },  /* The Pacific Ocean is the largest ocean on Ea... */
  { { 17117,277,49029,374,279,1375,4979,1992,389,1039,11580,13 }, 12 },  /* Antarctica is the coldest place on our planet. */
  { { 785,76190,10948,27455,1526,14867,1119,279,37685,15029,13 }, 11 },  /* The Nile River flows through Egypt into the ... */
  { { 44506,374,279,7772,3146,304,279,1879,553,3082,13 }, 11 },  /* Russia is the largest country in the world b... */
  { { 52854,16032,374,279,6722,3283,315,6323,13 }, 9 },  /* Tokyo is the capital city of Japan. */
  { { 785,75338,97340,8651,6747,504,279,2732,315,13622,13 }, 11 },  /* The Himalayas separate India from the rest o... */
  { { 7941,8930,279,6006,323,14858,1119,279,8205,9780,13 }, 11 },  /* She opened the door and walked into the warm... */
  { { 785,2841,6342,304,279,6118,3080,279,7015,3937,1495,13 }, 12 },  /* The children played in the park until the su... */
  { { 1519,12771,705,279,4540,323,2598,806,6554,13 }, 10 },  /* He picked up the phone and called his mother. */
  { { 785,22068,315,7722,10799,10199,279,4453,3753,13 }, 10 },  /* The smell of fresh coffee filled the entire ... */
  { { 6865,7578,3786,389,279,13425,10099,279,42984,13 }, 10 },  /* They sat together on the bench watching the ... */
  { { 785,2310,883,3229,7343,911,806,12537,553,279,3940,13 }, 12 },  /* The old man told stories about his youth by ... */
  { { 7941,6139,264,6524,311,1059,4238,879,12163,3041,3123,13 }, 12 },  /* She wrote a letter to her friend who lived f... */
  { { 785,5562,293,42061,53845,979,279,33958,24706,279,18126,13 }, 12 },  /* The dog barked loudly when the stranger appr... */
  { { 11510,6556,566,53144,15243,323,1349,279,16803,13 }, 10 },  /* Every morning he drank tea and read the news... */
  { { 785,2997,20190,2163,279,1965,369,7270,13856,13 }, 10 },  /* The family gathered around the table for Sun... */
  { { 12522,1052,572,264,3908,3743,879,10245,311,1349,6467,13 }, 12 },  /* Once there was a young girl who loved to rea... */
  { { 785,46609,23554,806,20214,323,16601,279,25105,75713,974,13 }, 12 },  /* The knight drew his sword and faced the drag... */
  { { 641,279,5538,13638,264,23335,2310,52269,15384,916,279,9898,13 }, 13 },  /* In the deep forest a wise old owl watched ov... */
  { { 785,8284,75744,3941,279,17951,8841,9788,11835,13 }, 10 },  /* The ship sailed across the ocean toward unkn... */
  { { 32,25382,33958,11465,304,279,14126,518,32333,13 }, 10 },  /* A mysterious stranger arrived in the village... */
  { { 785,31626,572,8177,23969,279,2310,37871,4916,13 }, 10 },  /* The treasure was hidden beneath the old oak ... */
  { { 7941,1730,264,10963,1376,429,8930,264,6234,6006,13 }, 11 },  /* She found a magic key that opened a secret d... */
  { { 785,11477,14275,264,18780,311,18383,279,23429,13 }, 10 },  /* The king declared a festival to celebrate th... */
  { { 32887,3123,264,25079,572,21286,553,264,3093,323,1101,27906,13 }, 13 },  /* Far away a kingdom was ruled by a kind and j... */
  { { 785,8171,56536,315,30978,7797,279,23501,13 }, 9 },  /* The boy dreamed of adventures beyond the mou... */
  { { 58022,388,990,7868,2038,1865,315,17516,323,6174,13 }, 11 },  /* Computers use binary code made of zeros and ... */
  { { 785,7602,33061,32051,315,7611,2163,279,1879,13 }, 10 },  /* The internet connects billions of devices ar... */
  { { 32,21511,646,1281,6738,3624,6605,323,1896,7249,13 }, 11 },  /* A smartphone can make calls send messages an... */
  { { 9286,16488,11229,8609,18495,3960,504,821,13 }, 9 },  /* Artificial intelligence helps computers lear... */
  { { 64865,9331,1598,389,26264,4518,315,45495,13 }, 9 },  /* Electric cars run on batteries instead of ga... */
  { { 34882,41660,26507,279,9237,323,1492,448,10646,13 }, 10 },  /* Satellites orbit the Earth and help with nav... */
  { { 14465,2412,646,2736,9079,429,525,11406,369,12677,13 }, 11 },  /* Robots can perform tasks that are dangerous ... */
  { { 785,1156,6366,572,438,2409,438,264,3054,13 }, 10 },  /* The first computer was as big as a room. */
  { { 19250,24198,3270,2038,311,1936,8357,13 }, 8 },  /* Software engineers write code to build appli... */
  { { 16055,24231,15354,1251,3553,821,389,8699,16293,13 }, 10 },  /* Cloud computing lets people store data on re... */
  { { 79071,34306,12499,39489,323,4879,23552,13 }, 8 },  /* Trees absorb carbon dioxide and release oxygen. */
  { { 3430,288,1281,25744,553,25895,308,38816,504,19281,13 }, 11 },  /* Bees make honey by collecting nectar from fl... */
  { { 785,17951,41938,37168,323,17066,10917,1817,1899,13 }, 10 },  /* The ocean tide rises and falls twice each day. */
  { { 65270,82,44566,311,44939,91299,2337,12406,13 }, 9 },  /* Birds migrate to warmer climates during winter. */
  { { 32,27968,76502,28475,1119,264,55169,4766,264,21690,9009,13 }, 12 },  /* A caterpillar transforms into a butterfly in... */
  { { 49,1945,6396,504,23501,1495,311,279,9396,13 }, 10 },  /* Rivers flow from mountains down to the sea. */
  { { 34,9819,91722,525,2114,311,9037,315,28591,9419,13 }, 11 },  /* Coral reefs are home to thousands of marine ... */
  { { 785,15584,2297,1576,279,9237,10266,2576,389,1181,8024,13 }, 12 },  /* The seasons change because the Earth tilts o... */
  { { 11092,36279,3410,22906,369,27601,9898,323,40811,13 }, 10 },  /* Forests provide shelter for countless animal... */
  { { 13911,1229,374,264,7988,9072,31543,304,279,12884,13 }, 11 },  /* Lightning is a powerful electric discharge i... */
  { { 39,66291,4041,504,2878,537,504,9250,2513,13 }, 10 },  /* Happiness comes from within not from externa... */
  { { 32,11618,315,264,16183,8756,12033,448,264,3175,3019,13 }, 12 },  /* A journey of a thousand miles begins with a ... */
  { { 785,4124,11958,37834,279,34211,714,279,2086,8644,5221,279,17163,13 }, 14 },  /* The early bird catches the worm but the seco... */
  { { 8747,7340,374,279,1850,15712,369,264,12421,4746,13 }, 11 },  /* Laughter is the best medicine for a sad heart. */
  { { 9064,1052,374,264,686,1052,374,2677,264,1616,13 }, 11 },  /* Where there is a will there is always a way. */
  { { 12948,6468,61796,1091,4244,3512,1410,13 }, 8 },  /* Actions speak louder than words ever could. */
  { { 11510,9437,702,264,14961,35371,421,498,1401,2588,3322,13 }, 12 },  /* Every cloud has a silver lining if you look ... */
  { { 785,16359,374,2677,2816,798,389,279,1008,3108,315,279,24650,13 }, 14 },  /* The grass is always greener on the other sid... */
  { { 1462,86984,678,33154,9583,13 }, 6 },  /* Time heals all wounds eventually. */
  { { 80334,374,2355,714,23389,374,14063,1246,311,990,432,13 }, 12 },  /* Knowledge is power but wisdom is knowing how... */
  { { 785,4746,42775,6543,1526,279,2487,1449,2086,13 }, 10 },  /* The heart pumps blood through the body every... */
  { { 52709,8609,2506,697,23648,323,24854,3746,13 }, 9 },  /* Exercise helps keep your muscles and bones s... */
  { { 41745,374,7565,369,1661,2820,323,2797,7274,13 }, 10 },  /* Sleep is essential for good health and clear... */
  { { 53,275,37825,1492,697,2487,729,10277,13 }, 9 },  /* Vitamins help your body function properly. */
  { { 785,4236,37107,525,13929,10778,22068,12656,323,5796,13 }, 11 },  /* The five senses are sight hearing smell tast... */
  { { 54,19049,697,6078,27934,279,8865,315,17239,1011,13 }, 11 },  /* Washing your hands prevents the spread of ge... */
  { { 785,29435,11554,279,2487,323,35136,5306,35753,13 }, 10 },  /* The skeleton supports the body and protects ... */
  { { 43,28122,1896,304,23552,323,4879,12499,39489,13 }, 10 },  /* Lungs take in oxygen and release carbon diox... */
  { { 8847,15736,3322,3015,374,2989,369,19429,9314,13 }, 10 },  /* Drinking enough water is important for stayi... */
  { { 785,6787,374,279,7772,2872,304,279,3738,2487,13 }, 11 },  /* The skin is the largest organ in the human b... */
  { { 33,878,374,1865,504,19828,3015,323,40480,13 }, 10 },  /* Bread is made from flour water and yeast. */
  { { 49,558,374,264,48956,3607,304,1657,14533,5837,13 }, 11 },  /* Rice is a staple food in many Asian countries. */
  { { 26843,2367,374,8947,553,2847,60316,14074,504,45166,476,70832,13 }, 13 },  /* Cheese is produced by curdling milk from cow... */
  { { 92964,4041,504,61788,26896,14700,304,34048,13604,13 }, 10 },  /* Chocolate comes from cocoa beans grown in tr... */
  { { 47318,56824,279,17172,315,3607,13 }, 7 },  /* Salt enhances the flavor of food. */
  { { 6639,64,374,1865,553,31266,287,15243,10901,304,4017,3015,13 }, 13 },  /* Tea is made by steeping tea leaves in hot wa... */
  { { 32,23831,9968,5646,27796,61245,323,23880,13 }, 9 },  /* A balanced diet includes proteins carbohydra... */
  { { 50,37074,374,264,10769,12000,1865,448,19653,323,7112,7640,13 }, 13 },  /* Sushi is a Japanese dish made with rice and ... */
  { { 39,2534,2581,19451,8669,323,646,1537,369,9037,315,1635,13 }, 13 },  /* Honey never spoils and can last for thousand... */
  { { 82280,26896,525,53562,1573,1660,4910,323,88095,13 }, 10 },  /* Coffee beans are roasted before being ground... */
  { { 8815,33705,374,279,4128,315,8038,323,14667,13 }, 10 },  /* Mathematics is the language of science and e... */
  { { 31899,6467,8609,9225,697,34918,323,6540,13 }, 9 },  /* Reading books helps expand your vocabulary a... */
  { { 785,6733,702,9037,315,6467,389,1449,3832,13 }, 10 },  /* The library has thousands of books on every ... */
  { { 32,11079,8609,4143,3535,501,18940,323,6708,13 }, 10 },  /* A teacher helps students understand new conc... */
  { { 13424,32892,601,911,279,20643,323,37486,82,315,279,3267,13 }, 13 },  /* History teaches us about the mistakes and tr... */
  { { 35400,21204,1492,601,6997,1246,279,1879,4278,13 }, 10 },  /* Science experiments help us discover how the... */
  { { 24128,6731,8609,2225,27597,323,25364,13 }, 8 },  /* Music education helps develop creativity and... */
  { { 47467,264,7214,4128,15885,501,14038,13 }, 8 },  /* Learning a foreign language opens new doors. */
  { { 88492,3643,4727,979,6832,894,501,9947,13 }, 9 },  /* Practice makes perfect when learning any new... */
  { { 9499,5696,374,279,3920,315,9237,323,1181,4419,13 }, 11 },  /* Geography is the study of Earth and its feat... */
  { { 59604,374,11245,369,279,468,3092,301,21938,323,6915,35005,13 }, 13 },  /* Paris is famous for the Eiffel Tower and fin... */
  { { 54950,1671,3947,14867,311,1490,279,13833,4510,86373,13 }, 11 },  /* Tourists visit Egypt to see the ancient pyra... */
  { { 32,25458,374,2567,369,6489,5821,13 }, 8 },  /* A passport is required for international tra... */
  { { 785,5426,55596,504,279,8056,518,6896,37145,13 }, 10 },  /* The train departed from the station at exact... */
  { { 20170,2010,3410,12026,369,39286,311,6084,323,2732,13 }, 11 },  /* Hotels provide rooms for travelers to sleep ... */
  { { 8373,1251,10702,311,5821,553,42924,1576,432,374,4937,13 }, 12 },  /* Some people prefer to travel by airplane bec... */
  { { 785,23971,12596,35036,504,13833,85469,13 }, 8 },  /* The museum displayed artifacts from ancient ... */
  { { 32,2415,8609,39286,1477,862,1616,304,49283,7482,13 }, 11 },  /* A map helps travelers find their way in unfa... */
  { { 57432,1037,16838,23974,601,315,279,7482,582,614,11994,13 }, 12 },  /* Souvenirs remind us of the places we have vi... */
  { { 785,11321,572,9761,448,4158,9278,323,2797,6303,3015,13 }, 12 },  /* The beach was covered with white sand and cl... */
  { { 43,908,525,2598,279,44519,315,279,44420,13 }, 10 },  /* Lions are called the kings of the jungle. */
  { { 35,337,39672,525,24514,55569,429,3887,304,279,17951,13 }, 12 },  /* Dolphins are intelligent mammals that live i... */
  { { 45339,52567,614,1293,489,15296,807,990,369,12182,323,16163,13 }, 13 },  /* Elephants have long trunks they use for eati... */
  { { 47,55358,3887,304,9255,13604,323,4157,11466,13 }, 10 },  /* Penguins live in cold regions and cannot fly. */
  { { 6406,13269,12616,80920,311,2287,40811,369,3607,13 }, 10 },  /* Spiders spin webs to catch insects for food. */
  { { 39,22434,614,1012,1483,553,12677,369,17903,369,23631,13 }, 12 },  /* Horses have been used by humans for transpor... */
  { { 64541,36297,1526,342,3305,4518,315,44174,13 }, 9 },  /* Fish breathe through gills instead of lungs. */
  { { 46,86,4730,525,92001,62450,19654,429,19073,518,3729,13 }, 12 },  /* Owls are nocturnal birds that hunt at night. */
  { { 17117,82,975,3786,304,47928,311,1936,862,95121,13 }, 11 },  /* Ants work together in colonies to build thei... */
  { { 1639,3831,525,279,7772,9898,429,614,3512,12163,13 }, 11 },  /* Whales are the largest animals that have eve... */
  { { 95912,11017,32438,1576,5112,34192,28393,1091,3100,13 }, 10 },  /* Thunder follows lightning because sound trav... */
  { { 97328,55195,525,7988,43483,429,1352,916,8205,17951,3015,13 }, 12 },  /* Hurricanes are powerful storms that form ove... */
  { { 62285,17066,979,279,9315,374,3685,42218,13 }, 9 },  /* Snow falls when the temperature is below fre... */
  { { 58818,374,8881,553,11799,304,3720,7262,13 }, 9 },  /* Wind is caused by differences in air pressure. */
  { { 37,538,374,264,9437,429,7586,3265,311,279,4910,13 }, 12 },  /* Fog is a cloud that forms close to the ground. */
  { { 32,92197,10953,1246,4017,476,9255,2494,374,13 }, 10 },  /* A thermometer measures how hot or cold somet... */
  { { 35,6344,82,3537,979,1052,374,537,3322,11174,369,264,1293,882,13 }, 15 },  /* Droughts happen when there is not enough rai... */
  { { 785,9104,17595,55878,3425,432,686,11174,476,32405,13 }, 11 },  /* The weather forecast predicts whether it wil... */
  { { 51330,7586,389,43136,979,12406,19879,5943,3685,7168,13 }, 11 },  /* Ice forms on lakes when winter temperatures ... */
  { { 59039,54531,4994,1283,11174,979,279,7015,4041,700,1549,13 }, 12 },  /* Rainbows appear after rain when the sun come... */
  { { 17999,374,13866,6785,6329,8225,13 }, 7 },  /* Zero is neither positive nor negative. */
  { { 32,21495,702,2326,11067,323,2326,25941,13 }, 9 },  /* A triangle has three sides and three angles. */
  { { 34767,374,13187,220,18,13,16,19,323,10868,279,11341,315,264,12671,13 }, 16 },  /* Pi is approximately 3.14 and represents the ... */
  { { 57251,1693,374,11504,5256,315,279,1852,1372,13 }, 10 },  /* Multiplication is repeated addition of the s... */
  { { 32,10250,1372,646,1172,387,17779,553,825,323,5086,13 }, 12 },  /* A prime number can only be divided by one an... */
  { { 785,1372,1849,582,990,374,2598,2331,5779,13 }, 10 },  /* The number system we use is called base ten. */
  { { 20787,7822,20816,12282,323,5888,315,3550,13 }, 9 },  /* Geometry studies shapes sizes and properties... */
  { { 78056,5136,4009,5479,315,264,4361,1372,13 }, 9 },  /* Fractions represent parts of a whole number. */
  { { 2082,23606,4933,429,1378,23393,525,6144,13 }, 9 },  /* An equation shows that two expressions are e... */
  { { 88464,10953,1246,4363,2494,374,311,3537,13 }, 9 },  /* Probability measures how likely something is... */
  { { 50,96188,374,279,1429,5411,10552,304,279,1879,13 }, 11 },  /* Soccer is the most popular sport in the world. */
  { { 785,24900,11610,525,5644,1449,3040,1635,13 }, 9 },  /* The Olympic Games are held every four years. */
  { { 73649,3959,4217,1430,311,2510,279,4935,1526,264,78671,13 }, 12 },  /* Basketball players try to throw the ball thr... */
  { { 13218,40033,374,2176,264,10552,323,264,19661,9947,13 }, 11 },  /* Swimming is both a sport and a survival skill. */
  { { 51,16156,374,6342,448,435,18382,323,264,2613,6176,4935,13 }, 13 },  /* Tennis is played with rackets and a small gr... */
  { { 18990,374,825,315,279,44548,7586,315,10158,13 }, 10 },  /* Running is one of the simplest forms of exer... */
  { { 88242,374,264,1809,315,8282,6342,389,264,4479,13 }, 11 },  /* Chess is a game of strategy played on a board. */
  { { 32,44696,374,264,6957,315,911,220,19,17,40568,13 }, 12 },  /* A marathon is a race of about 42 kilometers. */
  { { 1611,287,7460,8170,4628,323,48186,13 }, 8 },  /* Boxing requires strength speed and endurance. */
  { { 34,16021,374,1661,369,2820,323,279,4573,13 }, 10 },  /* Cycling is good for health and the environment. */
  { { 32,26278,702,220,23,23,6894,2670,4158,323,3691,6174,13 }, 13 },  /* A piano has 88 keys including white and blac... */
  { { 71992,1168,5242,479,63936,23983,7679,884,12826,304,220,16,23,23,24,13 }, 16 },  /* Vincent van Gogh painted Starry Night in 1889. */
  { { 24128,374,5326,1667,8388,389,264,5570,448,4236,5128,13 }, 12 },  /* Music is written using notes on a staff with... */
  { { 32,16986,702,4743,9069,429,8193,2155,10362,13 }, 10 },  /* A guitar has six strings that produce differ... */
  { { 785,98783,28556,374,264,11245,18824,553,65386,2994,96766,13 }, 12 },  /* The Mona Lisa is a famous painting by Leonar... */
  { { 2195,26320,12784,614,14158,369,9069,7579,86,8673,36038,323,83749,13 }, 14 },  /* Orchestras have sections for strings woodwin... */
  { { 52204,5696,40155,13943,304,882,1667,3100,13 }, 9 },  /* Photography captures moments in time using l... */
  { { 50,3314,417,552,374,279,1947,315,6825,2326,55887,7586,13 }, 13 },  /* Sculpture is the art of creating three dimen... */
  { { 35,681,32411,7203,36290,323,7493,13 }, 8 },  /* Dance combines movement rhythm and expression. */
  { { 32904,15149,5711,4244,311,1855,5335,323,21261,13 }, 10 },  /* Poetry uses words to create images and emoti... */
  { { 44,1561,374,2598,279,3731,28835,1576,315,1181,1894,13 }, 12 },  /* Mars is called the Red Planet because of its... */
  { { 785,17330,85128,279,9237,911,3055,1449,220,17,22,2849,13 }, 13 },  /* The Moon orbits the Earth about once every 2... */
  { { 61028,4384,35144,1576,862,3100,374,61136,553,279,16566,13 }, 12 },  /* Stars twinkle because their light is distort... */
  { { 32,33161,5610,32051,315,9759,323,32875,13 }, 9 },  /* A galaxy contains billions of stars and plan... */
  { { 41,19519,374,279,7772,11580,304,1039,12941,1849,13 }, 11 },  /* Jupiter is the largest planet in our solar s... */
  { { 1092,1415,525,1865,315,9853,15797,323,55517,18730,13 }, 11 },  /* Comets are made of ice dust and rocky partic... */
  { { 785,7179,11487,16629,85128,279,9237,13 }, 8 },  /* The International Space Station orbits the E... */
  { { 32,495,36064,82,9850,3281,27976,311,17697,304,3550,13 }, 12 },  /* Astronauts wear special suits to survive in ... */
  { { 14417,19766,525,13604,1380,23249,374,9016,3746,13 }, 10 },  /* Black holes are regions where gravity is ext... */
  { { 53,37865,374,279,37291,11580,304,1039,12941,1849,13 }, 11 },  /* Venus is the hottest planet in our solar sys... */
  { { 785,8866,389,279,7002,8542,432,572,7009,32333,13 }, 11 },  /* The clock on the wall showed it was nearly m... */
  { { 1519,15516,19472,279,8189,304,33866,5567,13 }, 9 },  /* He carefully wrapped the gift in colorful pa... */
  { { 785,13551,572,2480,315,2518,60641,323,4158,326,7597,13 }, 12 },  /* The garden was full of red roses and white l... */
  { { 7941,28240,264,6233,5492,429,7726,5019,311,23139,13 }, 11 },  /* She sang a beautiful song that moved everyon... */
  { { 785,2310,14164,27031,279,14796,3143,279,2613,14126,13 }, 11 },  /* The old bridge crossed the river near the sm... */
  { { 32,1661,2311,646,7557,498,311,2441,1879,13 }, 10 },  /* A good book can transport you to another world. */
  { { 785,11116,2598,369,1378,25374,315,19828,323,825,18636,13 }, 12 },  /* The recipe called for two cups of flour and ... */
  { { 1519,8356,279,10865,34986,448,264,2421,4285,7375,13 }, 11 },  /* He fixed the broken bicycle with a few simpl... */
  { { 785,3940,26626,75289,304,279,39411,678,3729,13 }, 10 },  /* The fire burned brightly in the fireplace al... */
  { { 7941,23983,1059,3054,264,8413,27501,315,6303,13 }, 10 },  /* She painted her room a soft shade of blue. */
  { { 785,6438,3855,389,882,323,35413,825,6460,13 }, 10 },  /* The meeting started on time and lasted one h... */
  { { 1519,1730,264,16254,389,279,41090,323,12771,432,705,13 }, 12 },  /* He found a coin on the sidewalk and picked i... */
  { { 785,8251,45398,66779,389,279,11030,483,13 }, 9 },  /* The cat slept peacefully on the windowsill. */
  { { 6865,27185,862,21582,518,264,6419,10729,13 }, 9 },  /* They celebrated their anniversary at a nice ... */
  { { 785,9956,41323,279,10901,3941,279,4287,8592,13 }, 10 },  /* The wind blew the leaves across the empty st... */
};
#endif
