/* Auto-generated by scripts/build_corpus.c — do not edit.
 * Pre-tokenized training corpus for STE fine-tuning (models/gpt2.c).
 * Source: scripts/corpus.txt  Tokenizer: prebuilt/gpt2_tokenizer.bin
 * Each entry: { int ids[32]; int n; }  (n = token count, <= 32)
 * Consume in gpt2.c:
 *   #include "train_data.h"
 *   for (i=0; i<N_TRAIN; i++) train_one(&train_data[i]);
 */
#ifndef TRAIN_DATA_H
#define TRAIN_DATA_H

#define MAX_TOK 32
static const struct { int ids[32]; int n; } train_data[] = {
  { { 464,3139,286,4881,318,6342,290,340,318,257,4950,1748,13}, 13 },  /* The capital of France is Paris and it is */
  { { 464,3139,286,2869,318,11790,543,318,257,845,8179,1295,13}, 13 },  /* The capital of Japan is Tokyo which is a */
  { { 464,3139,286,4486,318,11307,290,262,661,389,8030,13}, 12 },  /* The capital of Germany is Berlin and the */
  { { 464,3139,286,8031,318,10598,290,262,2057,318,7932,612,13}, 13 },  /* The capital of Italy is Rome and the foo */
  { { 464,3139,286,8602,318,14708,290,262,6193,318,1690,5814,13}, 13 },  /* The capital of Spain is Madrid and the w */
  { { 464,3139,286,3284,318,9070,290,45764,389,845,4692,13}, 12 },  /* The capital of Russia is Moscow and wint */
  { { 464,3139,286,2807,318,11618,290,340,468,257,890,2106,13}, 13 },  /* The capital of China is Beijing and it h */
  { { 464,3139,286,3794,318,968,12517,290,262,6483,389,18012,13}, 13 },  /* The capital of India is New Delhi and th */
  { { 464,3139,286,7595,318,39452,17517,407,15338,390,42799,13}, 12 },  /* The capital of Brazil is Brasilia not Ri */
  { { 464,3139,286,6365,318,23732,290,262,7850,38063,15623,832,340,13}, 14 },  /* The capital of Egypt is Cairo and the ri */
  { { 19184,40169,379,530,3470,7370,34186,379,5417,1241,13}, 11 },  /* Water boils at one hundred degrees Celsi */
  { { 464,3668,2925,1088,262,3825,1752,790,614,13}, 10 },  /* The Earth goes around the Sun once every */
  { { 15047,17781,845,3049,475,2128,17781,881,517,6364,13}, 11 },  /* Light travels very fast but sound travel */
  { { 20854,912,779,19606,284,787,511,898,2057,287,511,5667,13}, 13 },  /* Plants use sunlight to make their own fo */
  { { 464,1692,1767,468,734,3470,290,2237,11945,287,2472,13}, 12 },  /* The human body has two hundred and six b */
  { { 32,19972,468,734,5645,1444,262,5093,290,5366,24971,13}, 12 },  /* A magnet has two ends called the north a */
  { { 38208,35641,268,318,257,3623,326,356,761,284,18044,284,2652,6776,13}, 15 },  /* Oxygen is a gas that we need to breathe  */
  { { 464,6869,5640,262,46128,287,262,23744,286,262,3668,13}, 12 },  /* The Moon causes the tides in the oceans  */
  { { 32,27223,3568,287,262,6766,706,262,6290,319,257,27737,1110,13}, 14 },  /* A rainbow appears in the sky after the r */
  { { 27660,82,1011,287,6588,17556,290,1577,503,11863,329,514,13}, 13 },  /* Trees take in carbon dioxide and give ou */
  { { 464,6156,32658,3170,1588,27944,82,355,22234,82,329,21557,13}, 13 },  /* The ancient Egyptians built large pyrami */
  { { 22834,68,373,257,1049,13735,326,8879,881,286,2031,890,2084,13}, 14 },  /* Rome was a great empire that ruled much  */
  { { 464,13570,1803,373,15646,284,787,3835,881,11721,13}, 11 },  /* The printing press was invented to make  */
  { { 464,7825,373,15646,867,4138,286,812,878,5006,13}, 11 },  /* The wheel was invented many thousands of */
  { { 42912,290,38771,5615,287,49203,351,1029,7714,290,6941,1381,13}, 13 },  /* Kings and queens lived in castles with h */
  { { 33890,18526,3808,973,262,5788,284,1064,511,835,1973,262,23744,13}, 14 },  /* Sailors used the stars to find their way */
  { { 464,717,9061,547,845,1588,290,5901,2187,9519,13}, 11 },  /* The first computers were very large and  */
  { { 8061,1752,34275,4695,351,46842,925,286,4898,290,7815,13}, 12 },  /* People once hunted animals with spears m */
  { { 35965,11926,5281,23938,290,27952,1022,12899,8604,13}, 10 },  /* Trade routes carried silk and spices bet */
  { { 19620,35928,1364,2157,27081,290,19336,329,514,284,1100,13}, 12 },  /* Old civilizations left behind temples an */
  { { 40,588,284,4144,257,6508,286,6891,287,262,1903,3329,13}, 13 },  /* I like to drink a cup of coffee in the e */
  { { 3347,1816,284,262,1910,284,2822,4713,8234,290,13701,13}, 12 },  /* She went to the market to buy fresh frui */
  { { 464,1751,2826,287,262,3952,1566,262,4252,1816,866,13}, 12 },  /* The children played in the park until th */
  { { 1544,5969,262,5445,5118,351,257,15554,290,617,23361,13}, 12 },  /* He fixed the broken chair with a hammer  */
  { { 1135,550,8073,1978,290,6619,546,674,1110,379,670,13}, 12 },  /* We had dinner together and talked about  */
  { { 464,1323,373,2739,523,314,550,284,4043,287,262,4692,6290,13}, 14 },  /* The bus was late so I had to wait in the */
  { { 3666,18410,925,17141,351,9015,290,11464,329,514,13}, 11 },  /* My grandmother made soup with chicken an */
  { { 464,3290,4966,284,262,3420,618,340,2982,663,4870,2406,1363,13}, 14 },  /* The dog ran to the door when it heard it */
  { { 40,2626,616,8251,290,550,284,2989,262,2187,2156,329,606,13}, 14 },  /* I lost my keys and had to search the who */
  { { 2990,13055,262,7714,257,2705,4171,3124,284,787,340,9480,13}, 13 },  /* They painted the walls a soft blue color */
  { { 7454,2402,257,640,612,373,257,13239,416,262,5417,13}, 12 },  /* Once upon a time there was a kingdom by  */
  { { 7454,2402,257,640,257,1402,10441,5615,319,257,7331,8598,13}, 13 },  /* Once upon a time a small dragon lived on */
  { { 7454,2402,257,640,257,3595,18739,1043,257,6131,286,3869,13}, 13 },  /* Once upon a time a poor farmer found a b */
  { { 7454,2402,257,640,257,14169,21831,42608,257,19538,37593,13}, 12 },  /* Once upon a time a clever fox tricked a  */
  { { 7454,2402,257,640,257,1862,2576,14113,1290,284,5380,607,15807,13}, 14 },  /* Once upon a time a young girl traveled f */
  { { 7454,2402,257,640,257,5822,550,1115,11989,508,714,407,4236,13}, 14 },  /* Once upon a time a king had three sons w */
  { { 7454,2402,257,640,257,10787,1468,582,5615,2769,287,262,8222,13}, 14 },  /* Once upon a time a wise old man lived de */
  { { 7454,2402,257,640,257,22062,900,503,284,42596,257,7818,13824,13}, 14 },  /* Once upon a time a knight set out to sla */
  { { 7454,2402,257,640,257,20729,33835,284,257,12899,1956,329,25721,13}, 14 },  /* Once upon a time a merchant sailed to a  */
  { { 7454,2402,257,640,257,46721,2933,16896,17481,618,612,373,4844,13}, 14 },  /* Once upon a time a shepherd boy cried wo */
  { { 37573,4673,318,257,24637,286,11666,4430,1909,13}, 10 },  /* Machine learning is a subset of artifici */
  { { 32,3644,7000,1366,319,257,11898,393,287,663,4088,12014,13}, 13 },  /* A computer stores data on a disk or in i */
  { { 464,5230,20417,9061,477,1088,262,2187,995,13}, 10 },  /* The internet connects computers all arou */
  { { 32,11426,8781,734,661,1561,772,618,1290,5475,13}, 11 },  /* A telephone lets two people talk even wh */
  { { 9914,82,423,11874,326,4245,5252,284,787,606,1445,2651,13}, 13 },  /* Cars have engines that burn fuel to make */
  { { 32,4676,2753,257,4286,416,9616,1657,2121,319,257,12694,13}, 13 },  /* A camera takes a picture by letting ligh */
  { { 14350,1747,460,466,14262,393,4923,3946,329,1692,3259,13}, 12 },  /* Robots can do boring or dangerous jobs f */
  { { 44132,414,15623,832,19474,284,1176,674,7588,290,4410,13}, 12 },  /* Electricity flows through wires to power */
  { { 32,8801,3544,28713,393,24770,284,1394,2610,286,262,640,13}, 13 },  /* A clock uses gears or crystals to keep t */
  { { 25423,318,262,900,286,7729,326,4952,6890,644,284,466,13}, 13 },  /* Software is the set of instructions that */
  { { 464,6193,1909,318,27737,290,5814,351,257,10296,28633,13}, 12 },  /* The weather today is sunny and warm with */
  { { 818,7374,262,6729,8953,290,262,24768,16611,625,1327,13}, 12 },  /* In winter the snow falls and the lakes f */
  { { 30387,6774,649,12734,290,262,10087,1441,284,1702,13}, 11 },  /* Spring brings new flowers and the birds  */
  { { 33560,318,3024,290,262,1528,389,890,290,6016,13}, 11 },  /* Summer is hot and the days are long and  */
  { { 16541,4182,5667,1210,2266,290,3869,878,484,2121,284,262,2323,13}, 14 },  /* Autumn leaves turn red and gold before t */
  { { 32,6388,6774,18355,290,14357,290,4334,6290,13}, 10 },  /* A storm brings thunder and lightning and */
  { { 464,2344,17948,1327,477,1755,290,6265,257,5509,8478,13}, 12 },  /* The wind blew hard all night and broke a */
  { { 37,519,5017,262,19272,523,356,714,407,766,845,1290,4058,13}, 14 },  /* Fog covered the valley so we could not s */
  { { 3260,262,6290,262,1633,37609,4713,290,3424,290,6029,13}, 12 },  /* After the rain the air smelled fresh and */
  { { 464,11092,531,340,561,307,40026,475,340,750,407,6290,13}, 13 },  /* The forecast said it would be cloudy but */
  { { 464,2068,7586,21831,18045,625,262,16931,3290,287,262,12699,13}, 13 },  /* The quick brown fox jumps over the lazy  */
  { { 32,3797,460,766,287,262,3223,881,1365,621,257,1692,460,13}, 14 },  /* A cat can see in the dark much better th */
  { { 27991,8448,389,1913,4695,326,460,1057,845,3049,5600,13}, 12 },  /* Horses are strong animals that can run v */
  { { 39428,2107,287,1660,290,18044,832,308,2171,319,511,5389,13}, 13 },  /* Fish live in water and breathe through g */
  { { 42562,82,423,20596,11945,523,484,389,1657,1576,284,6129,13}, 13 },  /* Birds have hollow bones so they are ligh */
  { { 32,6842,44263,832,262,2187,7374,287,257,3223,11527,13}, 12 },  /* A bear sleeps through the whole winter i */
  { { 49512,82,787,12498,422,262,27576,18870,484,1064,287,262,12734,13}, 14 },  /* Bees make honey from the nectar they fin */
  { { 32304,684,2107,287,2628,1444,11293,82,319,262,1280,8701,1044,13}, 14 },  /* Lions live in groups called prides on th */
  { { 28827,33959,82,389,262,4387,4695,326,2513,319,262,1956,13}, 13 },  /* Elephants are the largest animals that w */
  { { 49795,82,466,407,423,7405,475,484,1445,845,2952,13}, 12 },  /* Snakes do not have legs but they move ve */
  { { 12679,324,318,925,422,10601,290,1660,290,20146,290,8268,13}, 13 },  /* Bread is made from flour and water and y */
  { { 2514,787,8887,345,12797,3024,1660,625,262,5667,290,4043,13}, 13 },  /* To make tea you pour hot water over the  */
  { { 7376,2771,318,925,422,7545,290,460,6938,7786,393,11607,13}, 13 },  /* Cheese is made from milk and can taste s */
  { { 49,501,318,257,2219,2057,287,867,2678,1088,262,995,13}, 13 },  /* Rice is a common food in many countries  */
  { { 32,922,17141,32857,82,6364,329,2250,319,262,27635,13}, 12 },  /* A good soup simmers slowly for hours on  */
  { { 16108,82,1663,319,7150,290,460,307,2266,393,4077,393,7872,13}, 14 },  /* Apples grow on trees and can be red or g */
  { { 7222,5853,16567,389,30490,878,484,389,2323,290,40163,13}, 12 },  /* Coffee beans are roasted before they are */
  { { 36,1130,82,460,307,29939,393,23018,393,34351,329,12607,13}, 13 },  /* Eggs can be boiled or fried or scrambled */
  { { 5606,4563,1838,2057,6029,475,1165,881,286,340,318,407,5448,13}, 14 },  /* Sugar makes food sweet but too much of i */
  { { 43061,6774,503,262,9565,286,2048,790,9433,356,4255,13}, 12 },  /* Salt brings out the flavor of almost eve */
  { { 464,2612,29019,2910,832,262,1767,477,1110,290,1755,13}, 12 },  /* The heart pumps blood through the body a */
  { { 1135,779,674,2951,284,766,290,674,11368,284,3285,262,995,13}, 14 },  /* We use our eyes to see and our ears to h */
  { { 9414,8023,534,9941,7622,606,3424,290,1913,290,2330,13}, 12 },  /* Brushing your teeth keeps them clean and */
  { { 40555,5419,262,1767,1334,290,262,2000,3505,1243,880,13}, 12 },  /* Sleep helps the body rest and the mind r */
  { { 16973,722,534,2832,9911,41171,82,422,1642,345,1254,6639,13}, 13 },  /* Washing your hands stops germs from maki */
  { { 464,3632,318,262,1618,326,8781,514,892,290,2193,290,1254,13}, 14 },  /* The brain is the organ that lets us thin */
  { { 10694,5427,651,7387,618,345,779,606,287,5517,1690,13}, 12 },  /* Muscles get stronger when you use them i */
  { { 49580,82,1577,262,1767,663,5485,290,1805,262,2705,3354,13}, 13 },  /* Bones give the body its shape and protec */
  { { 24602,3607,514,262,2568,356,761,284,1445,290,284,1663,13}, 13 },  /* Food gives us the energy we need to move */
  { { 20564,77,3364,1576,1660,318,1593,284,2652,5448,290,7995,13}, 13 },  /* Drinking enough water is important to st */
  { { 464,4512,5284,379,262,4429,655,878,5193,267,8801,13}, 12 },  /* The train arrived at the station just be */
  { { 1135,11856,674,11668,290,10357,284,262,12269,329,262,5041,13}, 13 },  /* We packed our bags and drove to the moun */
  { { 464,7541,2119,550,257,1570,286,262,5417,290,262,4634,4252,13}, 14 },  /* The hotel room had a view of the sea and */
  { { 32,3975,5419,345,1064,534,835,618,345,389,287,257,649,1295,13}, 15 },  /* A map helps you find your way when you a */
  { { 464,9003,373,18012,351,661,1016,284,867,4736,13}, 11 },  /* The airport was crowded with people goin */
  { { 3347,5839,257,7846,290,13488,319,262,3859,329,262,4512,13}, 13 },  /* She bought a ticket and waited on the pl */
  { { 464,2975,11699,510,262,12788,832,257,15715,4077,8222,13}, 12 },  /* The road wound up the hill through a den */
  { { 2990,1718,257,8848,1973,262,13546,284,3151,262,1402,7022,13}, 13 },  /* They took a boat across the lake to reac */
  { { 464,13257,373,1336,286,1468,21641,290,6283,5563,13}, 11 },  /* The museum was full of old paintings and */
  { { 32,5698,3751,514,1088,262,20073,290,1297,514,511,1621,13}, 13 },  /* A guide showed us around the ruins and t */
  { { 464,4701,2630,262,11483,319,262,3096,329,262,1398,13}, 12 },  /* The teacher wrote the lesson on the boar */
  { { 1544,3640,1327,790,1755,523,339,460,1208,262,2814,13}, 12 },  /* He studies hard every night so he can pa */
  { { 464,8860,1838,10012,326,389,2702,287,867,12437,13}, 11 },  /* The factory makes shoes that are sold in */
  { { 3347,2499,379,257,4436,810,673,5419,6639,661,13}, 11 },  /* She works at a hospital where she helps  */
  { { 464,3249,2067,2739,780,262,6478,373,7819,287,4979,13}, 12 },  /* The meeting started late because the bos */
  { { 28239,4376,511,2832,284,1265,262,4701,257,1808,13}, 11 },  /* Students raised their hands to ask the t */
  { { 464,6128,9808,379,5193,290,20612,379,2237,287,262,6180,13}, 13 },  /* The shop opens at nine and closes at six */
  { { 32,18739,34267,1903,284,3745,262,4695,878,262,17577,13}, 12 },  /* A farmer wakes early to feed the animals */
  { { 464,1074,3111,1978,284,5461,262,1628,319,640,13}, 11 },  /* The team worked together to finish the p */
  { { 464,2607,373,5897,780,2506,550,3750,1363,1541,13}, 11 },  /* The office was quiet because everyone ha */
  { { 1858,389,24742,4201,287,257,5664,290,24742,2431,287,281,1711,13}, 14 },  /* There are sixty seconds in a minute and  */
  { { 31334,1528,787,257,1285,290,15334,734,2745,787,257,614,13}, 13 },  /* Seven days make a week and fifty two wee */
  { { 32,8667,1724,14104,286,1223,588,9653,393,836,5500,13}, 12 },  /* A dozen means twelve of something like e */
  { { 464,8801,319,262,3355,3751,326,340,373,2063,1613,3478,13}, 13 },  /* The clock on the wall showed that it was */
  { { 32,4289,318,530,3470,812,890,355,356,954,262,640,13}, 13 },  /* A century is one hundred years long as w */
  { { 20588,468,12277,530,1528,655,588,2901,290,2932,466,13}, 12 },  /* December has thirty one days just like J */
  { { 1026,2753,262,3668,8208,1440,2250,284,7906,1088,1752,13}, 12 },  /* It takes the Earth twenty four hours to  */
  { { 464,1271,6632,373,257,845,1593,2126,287,19473,13}, 11 },  /* The number zero was a very important ide */
  { { 32,16470,614,2058,790,1440,812,290,468,281,3131,1110,13}, 13 },  /* A leap year comes every four years and h */
  { { 464,11845,5419,514,1394,2610,286,262,1528,290,262,1933,13}, 13 },  /* The calendar helps us keep track of the  */
  { { 3347,373,3772,618,607,1545,1625,284,3187,607,379,1363,13}, 13 },  /* She was happy when her friend came to vi */
  { { 1544,2936,6507,618,465,1468,3290,550,284,467,284,262,20202,13}, 14 },  /* He felt sad when his old dog had to go t */
  { { 32,922,1545,35019,618,345,423,1223,284,910,13}, 11 },  /* A good friend listens when you have some */
  { { 2990,13818,1978,379,262,8258,9707,262,25573,1297,13}, 11 },  /* They laughed together at the funny joke  */
  { { 464,1200,373,7787,286,262,3223,523,339,1364,257,1657,319,13}, 14 },  /* The child was afraid of the dark so he l */
  { { 1026,318,1611,284,1037,2130,508,468,9292,319,262,2323,13}, 13 },  /* It is kind to help someone who has falle */
  { { 1890,13992,257,1545,706,257,1907,1838,262,14738,1913,13}, 12 },  /* Forgiving a friend after a fight makes t */
  { { 464,26188,373,523,6568,326,663,2187,7894,714,407,2245,13}, 13 },  /* The puppy was so excited that its whole  */
  { { 32,8212,460,787,257,2089,1110,1254,257,1310,1643,1365,13}, 13 },  /* A smile can make a bad day feel a little */
  { { 18357,5508,351,661,12188,3774,625,257,890,640,13}, 11 },  /* Being honest with people builds trust ov */
  { { 32,24695,287,640,16031,5193,355,262,1468,2282,2925,13}, 12 },  /* A stitch in time saves nine as the old s */
  { { 8567,878,345,16470,523,345,466,407,2121,656,257,12840,13}, 13 },  /* Look before you leap so you do not fall  */
  { { 5211,407,5052,257,1492,416,262,3002,326,345,717,766,13}, 13 },  /* Do not judge a book by the cover that yo */
  { { 36423,290,11831,7864,262,3234,287,262,5863,1468,12838,13}, 12 },  /* Slow and steady wins the race in the fam */
  { { 2025,17180,257,1110,7622,262,6253,1497,340,318,1690,531,13}, 13 },  /* An apple a day keeps the doctor away it  */
  { { 8496,612,318,7523,612,318,3221,257,2046,1969,416,13}, 12 },  /* Where there is smoke there is usually a  */
  { { 464,1903,6512,17591,262,23849,355,262,36950,4952,514,13}, 12 },  /* The early bird catches the worm as the p */
  { { 23307,867,38383,20851,262,32051,618,2506,3382,1630,13}, 11 },  /* Too many cooks spoil the broth when ever */
  { { 32,7002,286,257,7319,4608,6140,351,530,1402,2239,13}, 12 },  /* A journey of a thousand miles begins wit */
  { { 12502,82,2740,27089,621,2456,326,661,1690,910,13}, 11 },  /* Actions speak louder than words that peo */
  { { 3347,34249,276,257,6576,422,16270,673,5839,379,262,6128,13}, 13 },  /* She sewed a dress from cloth she bought  */
  { { 1544,23470,257,13510,24556,422,257,3704,286,1468,26210,13}, 12 },  /* He carved a wooden spoon from a piece of */
  { { 464,1787,353,14292,262,21558,656,257,2835,290,7331,17379,13}, 13 },  /* The potter shaped the clay into a round  */
  { { 2990,3170,257,1402,2156,422,28902,290,1913,20534,13}, 11 },  /* They built a small house from bricks and */
  { { 32,15102,22947,37876,6953,1566,340,318,2266,290,788,339,8956,13}, 14 },  /* A blacksmith heats iron until it is red  */
  { { 1135,24650,3348,656,41175,82,284,11705,378,262,2119,329,262,2151,13}, 15 },  /* We folded paper into cranes to decorate  */
  { { 464,11376,263,18969,11904,287,15274,1973,262,3223,9260,13}, 12 },  /* The gardener planted seeds in rows acros */
  { { 3347,24486,303,257,7988,422,7888,22670,286,481,322,8478,13}, 13 },  /* She wove a basket from thin strips of wi */
  { { 1544,16524,262,10047,1566,790,4731,14846,655,826,13}, 11 },  /* He tuned the guitar until every string s */
  { { 464,34537,7668,7577,319,262,3096,284,651,262,826,17979,13}, 13 },  /* The painter mixed colors on the board to */
  { { 464,4097,2826,257,3496,326,925,2506,765,284,9280,13}, 12 },  /* The band played a song that made everyon */
  { { 3347,25889,257,2705,14009,981,673,3111,287,262,9592,13}, 12 },  /* She sang a soft tune while she worked in */
  { { 32,19132,468,2042,290,2330,8251,326,345,1803,284,711,13}, 13 },  /* A piano has black and white keys that yo */
  { { 464,38283,1838,257,1029,6029,2128,618,262,9563,318,7428,13}, 13 },  /* The violin makes a high sweet sound when */
  { { 6187,5700,1394,262,4405,326,262,584,12834,1061,13}, 11 },  /* Drums keep the beat that the other instr */
  { { 1544,9859,257,4286,286,262,8598,351,257,21613,290,3348,13}, 13 },  /* He drew a picture of the mountain with a */
  { { 464,42644,25889,1978,287,22471,379,262,3502,2139,13}, 11 },  /* The choir sang together in harmony at th */
  { { 32,6562,660,318,257,890,7888,12403,351,10421,1863,663,1735,13}, 14 },  /* A flute is a long thin tube with holes a */
  { { 464,6802,13055,262,6766,287,23787,286,11398,290,3869,13}, 12 },  /* The artist painted the sky in shades of  */
  { { 22648,460,787,514,1254,8716,393,24140,1231,597,2456,13}, 12 },  /* Music can make us feel joy or sorrow wit */
};
#define N_TRAIN (sizeof(train_data)/sizeof(train_data[0]))
#endif /* TRAIN_DATA_H */
